/**
 * MonnalisaWS.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package eu.monnalisa.pf;

public interface MonnalisaWS extends java.rmi.Remote {
    public int getQuantitaPrenotate(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public int getDisponibilitaSkuParziale(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public java.lang.String getDisponibilitaListaCategoriaAuth(java.lang.String sku_string, java.lang.String cod_magazzino, java.lang.String userid) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtendedSearchResult getDisponibilitaCollezione(java.lang.String cod_collezione, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public int getDisponibilita(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.MagazzinoResult[] getMagazzini(java.lang.String cliente, java.lang.String userid) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.OrdinaResult cambiaCliente(java.lang.String cart_id, java.lang.String cliente_old, java.lang.String cliente_new, java.lang.String userid) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtraInfoSearchResult getExtraInfoDisponibilitaProdotti(java.lang.String cod_collezione, java.lang.String cod_tipo_settore, java.lang.String cod_tipo_modello, java.lang.String cod_tema, java.lang.String cod_colore, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.SearchResultMag getDisponibilitaListaCategoriaTagliaColoreMagazzini(java.lang.String sku_string, java.lang.String taglia_string, java.lang.String colore_string, java.lang.String cod_magazzino, java.lang.String userid) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.SearchResult getSottoDisponibilitaTaglie(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_magazzino, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtraInfoSearchResult getExtraInfoDisponibilitaColore(java.lang.String cod_collezione, java.lang.String cod_tipo_settore, java.lang.String cod_tipo_modello, java.lang.String cod_tema, java.lang.String cod_colore, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public int notificaCambioStatoOrdine(java.lang.String stato, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public int notificaCambioStatoRigaOrdineSku(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id, java.lang.String stato, int qta) throws java.rmi.RemoteException;
    public java.lang.String getBarcodeFromSku(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtraInfoSearchResult getDisponibilitaMagazziniByBarcode(java.lang.String barcode, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.OrdinaResult ordina(java.lang.String cart_id, java.lang.String cliente, java.lang.String userid, boolean inizioPagamento) throws java.rmi.RemoteException;
    public Magento.SalesOrderEntityArray magentoGetListaFatture(java.lang.String username, java.lang.String apiKey, java.lang.String from, java.lang.String to) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtraInfoSearchResult getExtraInfoDisponibilitaLinea(java.lang.String cod_collezione, java.lang.String cod_tipo_settore, java.lang.String cod_tipo_modello, java.lang.String cod_tema, java.lang.String cod_colore, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.CartResult getPrenotazioniCarrello(java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public int cancellaPrenotazioneDaId(long cod_prenotazione, int qta, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.SearchResult getDisponibilitaListaCategoriaTagliaColore(java.lang.String sku_string, java.lang.String taglia_string, java.lang.String colore_string, java.lang.String cod_magazzino, java.lang.String userid) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.SearchResult getSottoDisponibilitaTaglieColori(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_magazzino, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public java.lang.String getDisponibilitaListaCategoria(java.lang.String sku_string) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.PrenotazioneResult prenotaArticoloEsteso(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, int qta, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id, int secondsBeforeExpiry, java.lang.String note) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtraInfoSearchResult getExtraInfoDisponibilitaTipologia(java.lang.String cod_collezione, java.lang.String cod_tipo_settore, java.lang.String cod_tipo_modello, java.lang.String cod_tema, java.lang.String cod_colore, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.PrenotazioneResult notificaCambioStatoRigaOrdineSplitSku(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id, java.lang.String stato, int qta) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.GenericResult getDisponibilitaMagazzini(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public java.lang.String magentoConfermaFattura(java.lang.String username, java.lang.String apiKey, java.lang.String codiceOrdine) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.PrenotazioneResult prenotaArticolo(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, int qta, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public int notificaCambioStatoRigaOrdine(java.lang.String stato, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, long cod_prenotazione, int qta) throws java.rmi.RemoteException;
    public int cancellaPrenotazione(java.lang.String cod_collezione, java.lang.String cod_modello, java.lang.String cod_articolo, java.lang.String cod_colore, java.lang.String cod_taglia, int qta, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtendedSearchResult getSottoDisponibilitaTaglieColoriSkuList(java.lang.String sku_string, java.lang.String cod_magazzino, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
    public eu.monnalisa.pf.ExtraInfoSearchResult getExtraInfoDisponibilitaTema(java.lang.String cod_collezione, java.lang.String cod_tipo_settore, java.lang.String cod_tipo_modello, java.lang.String cod_tema, java.lang.String cod_colore, java.lang.String cod_magazzino, java.lang.String cliente, java.lang.String userid, java.lang.String cart_id) throws java.rmi.RemoteException;
}
