// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ReturnOrderQueryDto.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Where.OpenApi.Purchase;

public final class ReturnOrderQueryDtoHolder extends Ice.ObjectHolderBase<ReturnOrderQueryDto>
{
    public
    ReturnOrderQueryDtoHolder()
    {
    }

    public
    ReturnOrderQueryDtoHolder(ReturnOrderQueryDto value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof ReturnOrderQueryDto)
        {
            value = (ReturnOrderQueryDto)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return ReturnOrderQueryDto.ice_staticId();
    }
}
