// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SopInfoAPIEntity.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Supplier;

public final class SopInfoAPIEntityHolder extends Ice.ObjectHolderBase<SopInfoAPIEntity>
{
    public
    SopInfoAPIEntityHolder()
    {
    }

    public
    SopInfoAPIEntityHolder(SopInfoAPIEntity value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof SopInfoAPIEntity)
        {
            value = (SopInfoAPIEntity)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return SopInfoAPIEntity.ice_staticId();
    }
}
