// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SopCurrencyIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.BaseDatas;

public final class SopCurrencyIcePrxHelper extends Ice.ObjectPrxHelperBase implements SopCurrencyIcePrx
{
    public static SopCurrencyIcePrx checkedCast(Ice.ObjectPrx __obj)
    {
        SopCurrencyIcePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SopCurrencyIcePrx)
            {
                __d = (SopCurrencyIcePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    SopCurrencyIcePrxHelper __h = new SopCurrencyIcePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SopCurrencyIcePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        SopCurrencyIcePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SopCurrencyIcePrx)
            {
                __d = (SopCurrencyIcePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    SopCurrencyIcePrxHelper __h = new SopCurrencyIcePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SopCurrencyIcePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SopCurrencyIcePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    SopCurrencyIcePrxHelper __h = new SopCurrencyIcePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SopCurrencyIcePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        SopCurrencyIcePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    SopCurrencyIcePrxHelper __h = new SopCurrencyIcePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SopCurrencyIcePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        SopCurrencyIcePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SopCurrencyIcePrx)
            {
                __d = (SopCurrencyIcePrx)__obj;
            }
            else
            {
                SopCurrencyIcePrxHelper __h = new SopCurrencyIcePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static SopCurrencyIcePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SopCurrencyIcePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            SopCurrencyIcePrxHelper __h = new SopCurrencyIcePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::BaseDatas::SopCurrencyIce"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _SopCurrencyIceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _SopCurrencyIceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, SopCurrencyIcePrx v)
    {
        __os.writeProxy(v);
    }

    public static SopCurrencyIcePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            SopCurrencyIcePrxHelper result = new SopCurrencyIcePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
