// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SopCategoryBrandAgreementPage.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.BaseDatas;

public final class SopCategoryBrandAgreementIcePrxHolder
{
    public
    SopCategoryBrandAgreementIcePrxHolder()
    {
    }

    public
    SopCategoryBrandAgreementIcePrxHolder(SopCategoryBrandAgreementIcePrx value)
    {
        this.value = value;
    }

    public SopCategoryBrandAgreementIcePrx value;
}
