
feign.hystrix.enabled: false
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
spring: 
  rabbitmq: 
           host: ${rabbitmq.host:172.20.11.49}
           port: 5672
           username: ephub-message-service
           password: ephub-message-service
           virtual-host: /ephub-message-service
  cloud: 
        consul: 
          host: localhost
          port: 8500
          discovery: 
            prefer-agent-address: true
            prefer-ip-address: true
            health-check-interval: 20s
            health-check-timeout: 15s
            register: true
            register-health-check: true
        stream: 
              bindings: 
                        pendingProductImportTask: 
                              destination: pending.product.import.task
                              group: one
                              consumer: 
                                       concurrency: 2
                                       maxAttempts: 1
                        hubProductImportTask: 
                              destination: hub.product.import.task
                              group: one
                              consumer: 
                                       concurrency: 2
                                       maxAttempts: 1
                        productExportTask: 
                              destination: product.export.task
                              group: one
                              consumer: 
                                       concurrency: 2
                                       maxAttempts: 1
                        supplierSkuSelectedProducer:
                             destination: supplier.sku.selected
                             content-type: application/json
                        supplierSkuSelectedConsumer:
                              destination: supplier.sku.selected
                              group: one
                              consumer:
                                       concurrency: 2
                                       maxAttempts: 1
                        pendingAuditProducer:
                            destination: supplier.spupending.audit
                            content-type: application/json
                        pendingAuditConsumer:
                             destination: supplier.spupending.audit
                             group: one
                             consumer:
                                      concurrency: 2
                                      maxAttempts: 1
              rabbit: 
                      bindings: 
                            pendingProductImportTask: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            hubProductImportTask: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            productExportTask: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            supplierSkuSelectedProducer:
                                 producer:
                                      prefix: HA.
                            supplierSkuSelectedConsumer:
                                 consumer:
                                      prefix: HA.
                                      autoBindDlq: false
                                      requeueRejected: true
                                      republishToDlq: false
                            pendingAuditProducer:
                                 producer:
                                      prefix: HA.
                            pendingAuditConsumer:
                                 consumer:
                                      prefix: HA.
                                      autoBindDlq: false
                                      requeueRejected: true
                                      republishToDlq: false
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8
  ftp:
       host: 172.20.10.88
       port: 21
       userName: ftpuser2
       password: shangpin@123
       ftpHubPath: /hub/
       ftpPendingPath: /pending/
       exportPath: /pending_export/
       studioPath: /studio_export/
       localResultPath: /usr/local/share/applications/asynchronous-task-consumer-service/ftp/
  #mail: 
       #default-recipient: yan_xiao_bin@126.com
       #default-sender: yanxiaobin@shangpin.com
       #default-encoding: UTF-8 # Default MimeMessage encoding.
       #host: smtp.263.net # SMTP server host. For instance `smtp.example.com`
       #port: 25 # SMTP server port.
       #protocol: smtp # Protocol used by the SMTP server.
       #username: yanxiaobin@shangpin.com # Login user of the SMTP server.
       #password: 123.com # Login password of the SMTP server.
       #test-connection: false # Test that the mail server is available on startup.
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).
shangpin: 
   hub: 
       callAddress: 
             pendingProductInfoUrl: http://scm.shangpin.com/gms/HubSupplierProduct/PendingProductInfo?productId=
             gmsAddProductUrl: http://scmapi.spidc1.com/gms/Product/AddProduct
             hubProductUrl: http://api-queue.ephub.spidc1.com/message/api/original-product
supplier: 
        params: 
              supplierName: zhicai
              supplierId: 2017031301866
              supplierNo: S0000864