
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.AnagraficaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfAnagraficaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloFlatExtLocaleVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloFlatExtVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloFlatVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloLocaleVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfCategoriaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfClasseVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfColoreVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfGruppoVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfLineaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfNazioneVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfRELSClassiSSCLassiVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfRelClassiSClassiVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfRelLineeClassiVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoCategoriaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoGruppoVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoSottoCategoriaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoSottoGruppoVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfTagliaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.DataPageVOOfAnagraficaVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.DocumentoVO;
import org.datacontract.schemas._2004._07.maximag_connector_vidra_service.MgDispo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IVidraSvcOfArticoloFlatExtVOArticoloFlatVO {


    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfTagliaVO
     */
    @WebMethod(operationName = "GetTaglie", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetTaglie")
    @WebResult(name = "GetTaglieResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTaglie", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTaglie")
    @ResponseWrapper(localName = "GetTaglieResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTaglieResponse")
    public ArrayOfTagliaVO getTaglie(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param date
     * @param usr
     * @param recordCount
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloFlatVO
     */
    @WebMethod(operationName = "GetArticoliFlat", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetArticoliFlat")
    @WebResult(name = "GetArticoliFlatResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetArticoliFlat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliFlat")
    @ResponseWrapper(localName = "GetArticoliFlatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliFlatResponse")
    public ArrayOfArticoloFlatVO getArticoliFlat(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date,
        @WebParam(name = "recordCount", targetNamespace = "http://tempuri.org/")
        Integer recordCount);

    /**
     * 
     * @param filter
     * @param date
     * @param pageNumber
     * @param usr
     * @param recordCount
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloFlatExtVO
     */
    @WebMethod(operationName = "GetArticoliFlatExtByDate", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetArticoliFlatExtByDate")
    @WebResult(name = "GetArticoliFlatExtByDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetArticoliFlatExtByDate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliFlatExtByDate")
    @ResponseWrapper(localName = "GetArticoliFlatExtByDateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliFlatExtByDateResponse")
    public ArrayOfArticoloFlatExtVO getArticoliFlatExtByDate(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        String filter,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date,
        @WebParam(name = "recordCount", targetNamespace = "http://tempuri.org/")
        Integer recordCount,
        @WebParam(name = "pageNumber", targetNamespace = "http://tempuri.org/")
        Integer pageNumber);

    /**
     * 
     * @param filter
     * @param date
     * @param pageNumber
     * @param usr
     * @param recordCount
     * @param language
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloFlatExtLocaleVO
     */
    @WebMethod(operationName = "GetArticoliFlatExtLocaleByDate", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetArticoliFlatExtLocaleByDate")
    @WebResult(name = "GetArticoliFlatExtLocaleByDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetArticoliFlatExtLocaleByDate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliFlatExtLocaleByDate")
    @ResponseWrapper(localName = "GetArticoliFlatExtLocaleByDateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliFlatExtLocaleByDateResponse")
    public ArrayOfArticoloFlatExtLocaleVO getArticoliFlatExtLocaleByDate(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        String filter,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date,
        @WebParam(name = "recordCount", targetNamespace = "http://tempuri.org/")
        Integer recordCount,
        @WebParam(name = "pageNumber", targetNamespace = "http://tempuri.org/")
        Integer pageNumber,
        @WebParam(name = "language", targetNamespace = "http://tempuri.org/")
        String language);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfColoreVO
     */
    @WebMethod(operationName = "GetColori", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetColori")
    @WebResult(name = "GetColoriResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetColori", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetColori")
    @ResponseWrapper(localName = "GetColoriResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetColoriResponse")
    public ArrayOfColoreVO getColori(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfNazioneVO
     */
    @WebMethod(operationName = "GetNazioni", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetNazioni")
    @WebResult(name = "GetNazioniResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNazioni", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNazioni")
    @ResponseWrapper(localName = "GetNazioniResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNazioniResponse")
    public ArrayOfNazioneVO getNazioni(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @param order
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertOrderItalist", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/InsertOrderItalist")
    @WebResult(name = "InsertOrderItalistResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertOrderItalist", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertOrderItalist")
    @ResponseWrapper(localName = "InsertOrderItalistResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertOrderItalistResponse")
    public String insertOrderItalist(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "order", targetNamespace = "http://tempuri.org/")
        DocumentoVO order);

    /**
     * 
     * @param usr
     * @param pwd
     * @param order
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertOrder", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/InsertOrder")
    @WebResult(name = "InsertOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertOrder")
    @ResponseWrapper(localName = "InsertOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertOrderResponse")
    public String insertOrder(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "order", targetNamespace = "http://tempuri.org/")
        DocumentoVO order);

    /**
     * 
     * @param usr
     * @param cdMagazzino
     * @param pwd
     * @param barCode
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.MgDispo
     */
    @WebMethod(operationName = "GetDispoByBarcode", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetDispoByBarcode")
    @WebResult(name = "GetDispoByBarcodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDispoByBarcode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDispoByBarcode")
    @ResponseWrapper(localName = "GetDispoByBarcodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDispoByBarcodeResponse")
    public MgDispo getDispoByBarcode(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "barCode", targetNamespace = "http://tempuri.org/")
        String barCode,
        @WebParam(name = "cdMagazzino", targetNamespace = "http://tempuri.org/")
        String cdMagazzino);

    /**
     * 
     * @param usr
     * @param pwd
     * @param customer
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertCustomer", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/InsertCustomer")
    @WebResult(name = "InsertCustomerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertCustomer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertCustomer")
    @ResponseWrapper(localName = "InsertCustomerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertCustomerResponse")
    public String insertCustomer(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "customer", targetNamespace = "http://tempuri.org/")
        AnagraficaVO customer);

    /**
     * 
     * @param offset
     * @param usr
     * @param pageSize
     * @param nome
     * @param id
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.DataPageVOOfAnagraficaVO
     */
    @WebMethod(operationName = "GetPagedCustomer", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetPagedCustomer")
    @WebResult(name = "GetPagedCustomerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPagedCustomer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPagedCustomer")
    @ResponseWrapper(localName = "GetPagedCustomerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPagedCustomerResponse")
    public DataPageVOOfAnagraficaVO getPagedCustomer(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "nome", targetNamespace = "http://tempuri.org/")
        String nome,
        @WebParam(name = "pageSize", targetNamespace = "http://tempuri.org/")
        Integer pageSize,
        @WebParam(name = "offset", targetNamespace = "http://tempuri.org/")
        Integer offset);

    /**
     * 
     * @param offset
     * @param usr
     * @param pagesize
     * @param nome
     * @param id
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfAnagraficaVO
     */
    @WebMethod(operationName = "GetCustomer", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetCustomer")
    @WebResult(name = "GetCustomerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomer")
    @ResponseWrapper(localName = "GetCustomerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerResponse")
    public ArrayOfAnagraficaVO getCustomer(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "nome", targetNamespace = "http://tempuri.org/")
        String nome,
        @WebParam(name = "pagesize", targetNamespace = "http://tempuri.org/")
        Integer pagesize,
        @WebParam(name = "offset", targetNamespace = "http://tempuri.org/")
        Integer offset);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetLastRecordCount", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetLastRecordCount")
    @WebResult(name = "GetLastRecordCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLastRecordCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastRecordCount")
    @ResponseWrapper(localName = "GetLastRecordCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastRecordCountResponse")
    public Integer getLastRecordCount();

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfCategoriaVO
     */
    @WebMethod(operationName = "GetCategorie", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetCategorie")
    @WebResult(name = "GetCategorieResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCategorie", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCategorie")
    @ResponseWrapper(localName = "GetCategorieResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCategorieResponse")
    public ArrayOfCategoriaVO getCategorie(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoCategoriaVO
     */
    @WebMethod(operationName = "GetSottoCategorie", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetSottoCategorie")
    @WebResult(name = "GetSottoCategorieResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSottoCategorie", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoCategorie")
    @ResponseWrapper(localName = "GetSottoCategorieResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoCategorieResponse")
    public ArrayOfSottoCategoriaVO getSottoCategorie(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoSottoCategoriaVO
     */
    @WebMethod(operationName = "GetSottoSottoCategorie", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetSottoSottoCategorie")
    @WebResult(name = "GetSottoSottoCategorieResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSottoSottoCategorie", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoSottoCategorie")
    @ResponseWrapper(localName = "GetSottoSottoCategorieResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoSottoCategorieResponse")
    public ArrayOfSottoSottoCategoriaVO getSottoSottoCategorie(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfGruppoVO
     */
    @WebMethod(operationName = "GetGruppoVO", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetGruppoVO")
    @WebResult(name = "GetGruppoVOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGruppoVO", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGruppoVO")
    @ResponseWrapper(localName = "GetGruppoVOResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGruppoVOResponse")
    public ArrayOfGruppoVO getGruppoVO(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoGruppoVO
     */
    @WebMethod(operationName = "GetSottoGruppo", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetSottoGruppo")
    @WebResult(name = "GetSottoGruppoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSottoGruppo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoGruppo")
    @ResponseWrapper(localName = "GetSottoGruppoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoGruppoResponse")
    public ArrayOfSottoGruppoVO getSottoGruppo(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfSottoSottoGruppoVO
     */
    @WebMethod(operationName = "GetSottoSottoGruppo", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetSottoSottoGruppo")
    @WebResult(name = "GetSottoSottoGruppoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSottoSottoGruppo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoSottoGruppo")
    @ResponseWrapper(localName = "GetSottoSottoGruppoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSottoSottoGruppoResponse")
    public ArrayOfSottoSottoGruppoVO getSottoSottoGruppo(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfClasseVO
     */
    @WebMethod(operationName = "GetItemLines", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetItemLines")
    @WebResult(name = "GetItemLinesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemLines", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetItemLines")
    @ResponseWrapper(localName = "GetItemLinesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetItemLinesResponse")
    public ArrayOfClasseVO getItemLines(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfLineaVO
     */
    @WebMethod(operationName = "GetItemClasses", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetItemClasses")
    @WebResult(name = "GetItemClassesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemClasses", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetItemClasses")
    @ResponseWrapper(localName = "GetItemClassesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetItemClassesResponse")
    public ArrayOfLineaVO getItemClasses(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfRelLineeClassiVO
     */
    @WebMethod(operationName = "GetRelationsLineeClassi", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetRelationsLineeClassi")
    @WebResult(name = "GetRelationsLineeClassiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRelationsLineeClassi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRelationsLineeClassi")
    @ResponseWrapper(localName = "GetRelationsLineeClassiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRelationsLineeClassiResponse")
    public ArrayOfRelLineeClassiVO getRelationsLineeClassi(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfRelClassiSClassiVO
     */
    @WebMethod(operationName = "GetRelationsClassiSClassi", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetRelationsClassiSClassi")
    @WebResult(name = "GetRelationsClassiSClassiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRelationsClassiSClassi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRelationsClassiSClassi")
    @ResponseWrapper(localName = "GetRelationsClassiSClassiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRelationsClassiSClassiResponse")
    public ArrayOfRelClassiSClassiVO getRelationsClassiSClassi(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param usr
     * @param pwd
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfRELSClassiSSCLassiVO
     */
    @WebMethod(operationName = "GetRelationsSClassiSSClassi", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetRelationsSClassiSSClassi")
    @WebResult(name = "GetRelationsSClassiSSClassiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRelationsSClassiSSClassi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRelationsSClassiSSClassi")
    @ResponseWrapper(localName = "GetRelationsSClassiSSClassiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRelationsSClassiSSClassiResponse")
    public ArrayOfRELSClassiSSCLassiVO getRelationsSClassiSSClassi(
        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        String usr,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.maximag_connector_vidra_service.ArrayOfArticoloLocaleVO
     */
    @WebMethod(operationName = "GetArticoliLocale", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetArticoliLocale")
    @WebResult(name = "GetArticoliLocaleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetArticoliLocale", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliLocale")
    @ResponseWrapper(localName = "GetArticoliLocaleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetArticoliLocaleResponse")
    public ArrayOfArticoloLocaleVO getArticoliLocale();

    /**
     * 
     * @param valuta
     * @param data
     * @return
     *     returns java.lang.Float
     */
    @WebMethod(operationName = "GetTassoCambio", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/GetTassoCambio")
    @WebResult(name = "GetTassoCambioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTassoCambio", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTassoCambio")
    @ResponseWrapper(localName = "GetTassoCambioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTassoCambioResponse")
    public Float getTassoCambio(
        @WebParam(name = "valuta", targetNamespace = "http://tempuri.org/")
        String valuta,
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar data);

    /**
     * 
     */
    @WebMethod(operationName = "ExportItalist", action = "http://tempuri.org/IVidraSvcOf_ArticoloFlatExtVO_ArticoloFlatVO/ExportItalist")
    @RequestWrapper(localName = "ExportItalist", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExportItalist")
    @ResponseWrapper(localName = "ExportItalistResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExportItalistResponse")
    public void exportItalist();

}
