// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SopSupplierProductInventoryIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Product;

public class SopSupplierProductInventoryIce extends Ice.ObjectImpl
{
    public SopSupplierProductInventoryIce()
    {
    }

    public SopSupplierProductInventoryIce(int SopSkuNo, String SkuName, String SupplierSkuNo, String ProductModel, String BrandNo, String BrandName, String CategoryNo, String CategoryName, int SkuStatus, String SkuStatusName, String WarehouseNo, String WarehouseName, int InventoryQuantity, int RealInventoryQuantity, int LockInventoryQuantity, int PrewarningQuantity, int SupplyCycle, int InventoryStatus, String SupplierNo, String SkuNo, String BarCode, long SopUserNo, String Freight, int FreightCurrency, String OriginalPrice, int OriginalCurrency)
    {
        this.SopSkuNo = SopSkuNo;
        this.SkuName = SkuName;
        this.SupplierSkuNo = SupplierSkuNo;
        this.ProductModel = ProductModel;
        this.BrandNo = BrandNo;
        this.BrandName = BrandName;
        this.CategoryNo = CategoryNo;
        this.CategoryName = CategoryName;
        this.SkuStatus = SkuStatus;
        this.SkuStatusName = SkuStatusName;
        this.WarehouseNo = WarehouseNo;
        this.WarehouseName = WarehouseName;
        this.InventoryQuantity = InventoryQuantity;
        this.RealInventoryQuantity = RealInventoryQuantity;
        this.LockInventoryQuantity = LockInventoryQuantity;
        this.PrewarningQuantity = PrewarningQuantity;
        this.SupplyCycle = SupplyCycle;
        this.InventoryStatus = InventoryStatus;
        this.SupplierNo = SupplierNo;
        this.SkuNo = SkuNo;
        this.BarCode = BarCode;
        this.SopUserNo = SopUserNo;
        this.Freight = Freight;
        this.FreightCurrency = FreightCurrency;
        this.OriginalPrice = OriginalPrice;
        this.OriginalCurrency = OriginalCurrency;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new SopSupplierProductInventoryIce();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Product::SopSupplierProductInventoryIce"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.writeInt(SopSkuNo);
        __os.writeString(SkuName);
        __os.writeString(SupplierSkuNo);
        __os.writeString(ProductModel);
        __os.writeString(BrandNo);
        __os.writeString(BrandName);
        __os.writeString(CategoryNo);
        __os.writeString(CategoryName);
        __os.writeInt(SkuStatus);
        __os.writeString(SkuStatusName);
        __os.writeString(WarehouseNo);
        __os.writeString(WarehouseName);
        __os.writeInt(InventoryQuantity);
        __os.writeInt(RealInventoryQuantity);
        __os.writeInt(LockInventoryQuantity);
        __os.writeInt(PrewarningQuantity);
        __os.writeInt(SupplyCycle);
        __os.writeInt(InventoryStatus);
        __os.writeString(SupplierNo);
        __os.writeString(SkuNo);
        __os.writeString(BarCode);
        __os.writeLong(SopUserNo);
        __os.writeString(Freight);
        __os.writeInt(FreightCurrency);
        __os.writeString(OriginalPrice);
        __os.writeInt(OriginalCurrency);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        SopSkuNo = __is.readInt();
        SkuName = __is.readString();
        SupplierSkuNo = __is.readString();
        ProductModel = __is.readString();
        BrandNo = __is.readString();
        BrandName = __is.readString();
        CategoryNo = __is.readString();
        CategoryName = __is.readString();
        SkuStatus = __is.readInt();
        SkuStatusName = __is.readString();
        WarehouseNo = __is.readString();
        WarehouseName = __is.readString();
        InventoryQuantity = __is.readInt();
        RealInventoryQuantity = __is.readInt();
        LockInventoryQuantity = __is.readInt();
        PrewarningQuantity = __is.readInt();
        SupplyCycle = __is.readInt();
        InventoryStatus = __is.readInt();
        SupplierNo = __is.readString();
        SkuNo = __is.readString();
        BarCode = __is.readString();
        SopUserNo = __is.readLong();
        Freight = __is.readString();
        FreightCurrency = __is.readInt();
        OriginalPrice = __is.readString();
        OriginalCurrency = __is.readInt();
        __is.endReadSlice();
    }

    public int SopSkuNo;

    public String SkuName;

    public String SupplierSkuNo;

    public String ProductModel;

    public String BrandNo;

    public String BrandName;

    public String CategoryNo;

    public String CategoryName;

    public int SkuStatus;

    public String SkuStatusName;

    public String WarehouseNo;

    public String WarehouseName;

    public int InventoryQuantity;

    public int RealInventoryQuantity;

    public int LockInventoryQuantity;

    public int PrewarningQuantity;

    public int SupplyCycle;

    public int InventoryStatus;

    public String SupplierNo;

    public String SkuNo;

    public String BarCode;

    public long SopUserNo;

    public String Freight;

    public int FreightCurrency;

    public String OriginalPrice;

    public int OriginalCurrency;

    public static final long serialVersionUID = -709124433L;
}
