// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SpfProductAttributeInfoIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Product;

public class SpfProductAttributeInfoIce extends Ice.ObjectImpl
{
    public SpfProductAttributeInfoIce()
    {
    }

    public SpfProductAttributeInfoIce(int TemplateId, int AttibuteId, String AttrName, int AttrInputType, int AttrSortId, short ApplyType, short IsBackRequired, int ParentId, java.util.List<SpfProductAttributeValueInfo> AttributeValueList)
    {
        this.TemplateId = TemplateId;
        this.AttibuteId = AttibuteId;
        this.AttrName = AttrName;
        this.AttrInputType = AttrInputType;
        this.AttrSortId = AttrSortId;
        this.ApplyType = ApplyType;
        this.IsBackRequired = IsBackRequired;
        this.ParentId = ParentId;
        this.AttributeValueList = AttributeValueList;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new SpfProductAttributeInfoIce();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Product::SpfProductAttributeInfoIce"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.writeInt(TemplateId);
        __os.writeInt(AttibuteId);
        __os.writeString(AttrName);
        __os.writeInt(AttrInputType);
        __os.writeInt(AttrSortId);
        __os.writeShort(ApplyType);
        __os.writeShort(IsBackRequired);
        __os.writeInt(ParentId);
        SpfProductAttributeValueInfoListHelper.write(__os, AttributeValueList);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        TemplateId = __is.readInt();
        AttibuteId = __is.readInt();
        AttrName = __is.readString();
        AttrInputType = __is.readInt();
        AttrSortId = __is.readInt();
        ApplyType = __is.readShort();
        IsBackRequired = __is.readShort();
        ParentId = __is.readInt();
        AttributeValueList = SpfProductAttributeValueInfoListHelper.read(__is);
        __is.endReadSlice();
    }

    public int TemplateId;

    public int AttibuteId;

    public String AttrName;

    public int AttrInputType;

    public int AttrSortId;

    public short ApplyType;

    public short IsBackRequired;

    public int ParentId;

    public java.util.List<SpfProductAttributeValueInfo> AttributeValueList;

    public static final long serialVersionUID = 574481478L;
}
