// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Supply.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Product;

public final class SupplyPrxHelper extends Ice.ObjectPrxHelperBase implements SupplyPrx
{
    public static SupplyPrx checkedCast(Ice.ObjectPrx __obj)
    {
        SupplyPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SupplyPrx)
            {
                __d = (SupplyPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    SupplyPrxHelper __h = new SupplyPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SupplyPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        SupplyPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SupplyPrx)
            {
                __d = (SupplyPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    SupplyPrxHelper __h = new SupplyPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static SupplyPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SupplyPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    SupplyPrxHelper __h = new SupplyPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SupplyPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        SupplyPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    SupplyPrxHelper __h = new SupplyPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static SupplyPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        SupplyPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof SupplyPrx)
            {
                __d = (SupplyPrx)__obj;
            }
            else
            {
                SupplyPrxHelper __h = new SupplyPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static SupplyPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        SupplyPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            SupplyPrxHelper __h = new SupplyPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Product::Supply"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _SupplyDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _SupplyDelD();
    }

    public static void __write(IceInternal.BasicStream __os, SupplyPrx v)
    {
        __os.writeProxy(v);
    }

    public static SupplyPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            SupplyPrxHelper result = new SupplyPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
