package com.shangpin.iog.forzieri.dto;

import java.util.Map;

public class CategoryMap {
	private Map<String,String> categoryMap;
	public CategoryMap(){
		categoryMap.put("999903","Bags");
		categoryMap.put("999904","Jewelry");
		categoryMap.put("999905","Home Decor");
		categoryMap.put("999906","Shoes");
		categoryMap.put("999907","Accessories");
		categoryMap.put("999909","Clothing");
		categoryMap.put("999910","Travel & Business");
		categoryMap.put("888820","Scarves");
		categoryMap.put("888801","Men's Jewelry");
		categoryMap.put("18","Handbags");
		categoryMap.put("108","Men's Bags");
		categoryMap.put("11","Button Covers");
		categoryMap.put("10","Cufflinks");
		categoryMap.put("88","Men's Bracelets");
		categoryMap.put("90","Men's Necklaces");
		categoryMap.put("87","Men's Rings");
		categoryMap.put("85","Money Clips & Key Rings");
		categoryMap.put("12","Tie Clips");
		categoryMap.put("31","Vintage Cufflinks");
		categoryMap.put("86","Writing Instruments");
		categoryMap.put("83","Biker Vibe");
		categoryMap.put("60","Bracelets");
		categoryMap.put("63","Brooches & Pins");
		categoryMap.put("38","Cameo");
		categoryMap.put("59","Earrings");
		categoryMap.put("121","Fine Watches");
		categoryMap.put("66","Jeweled Belts");
		categoryMap.put("64","Keychains");
		categoryMap.put("84","Men's Watches");
		categoryMap.put("62","Modular Jewelry");
		categoryMap.put("58","Necklaces");
		categoryMap.put("61","Pendants");
		categoryMap.put("70","Rings");
		categoryMap.put("33","Women's Watches");
		categoryMap.put("72","Bath");
		categoryMap.put("76","Decor & Lighting");
		categoryMap.put("29","Desk Accessories");
		categoryMap.put("28","Jewelry Boxes");
		categoryMap.put("71","Kitchen & Dining");
		categoryMap.put("105","Murano Accents");
		categoryMap.put("110","Music Boxes");
		categoryMap.put("34","Paintings");
		categoryMap.put("69","Picture Frames & Albums");
		categoryMap.put("67","Silver Giftware");
		categoryMap.put("30","Smoking Accessories");
		categoryMap.put("65","Watch Cases");
		categoryMap.put("109","Writing Instruments");
		categoryMap.put("73","Shoes");
		categoryMap.put("75","Men's Shoes");
		categoryMap.put("6","Bandanas");
		categoryMap.put("3","Long Scarves");
		categoryMap.put("14","Pashmina");
		categoryMap.put("9","Shawls & Wraps");
		categoryMap.put("2","Square Scarves");
		categoryMap.put("7","Ascot ties");
		categoryMap.put("8","Bowties and Cummerbunds");
		categoryMap.put("17","Extra-Long Ties");
		categoryMap.put("51","Handkerchiefs");
		categoryMap.put("117","Key Holders");
		categoryMap.put("118","Key Holders");
		categoryMap.put("22","Men's Belts");
		categoryMap.put("32","Men's Gloves");
		categoryMap.put("36","Men's Hats");
		categoryMap.put("4","Men's Scarves");
		categoryMap.put("16","Narrow Ties");
		categoryMap.put("13","Pocket Squares");
		categoryMap.put("113","Small Leather Goods");
		categoryMap.put("114","Small Leather Goods");
		categoryMap.put("80","Sunglasses");
		categoryMap.put("81","Sunglasses");
		categoryMap.put("1","Ties");
		categoryMap.put("112","Wallets");
		categoryMap.put("115","Wallets");
		categoryMap.put("52","Women's Belts");
		categoryMap.put("53","Women's Gloves");
		categoryMap.put("50","Women's Hats");
		categoryMap.put("68","Dress Shirts");
		categoryMap.put("77","Leather Jackets");
		categoryMap.put("79","Leather Jackets");
		categoryMap.put("107","Outerwear");
		categoryMap.put("106","Outerwear & Furs");
		categoryMap.put("104","Polo Shirts");
		categoryMap.put("74","Sweaters");
		categoryMap.put("82","Tops & Co");
		categoryMap.put("111","Baby Collection");
		categoryMap.put("56","Backpacks");
		categoryMap.put("19","Briefcases");
		categoryMap.put("55","Coin Holders");
		categoryMap.put("120","Desk Accessories");
		categoryMap.put("24","Doctor Bags");
		categoryMap.put("27","Golf World");
		categoryMap.put("54","Key Holders");
		categoryMap.put("26","Small Leather Goods");
		categoryMap.put("37","Tie Cases");
		categoryMap.put("20","Travel Bags");
		categoryMap.put("25","Wallets");
		categoryMap.put("119","Watch Cases");
		categoryMap.put("78","Wine Cases");
		categoryMap.put("116","Writing Instruments");
		categoryMap.put("0013-1","Backpack");
		categoryMap.put("0013-5","Bucket");
		categoryMap.put("0013-9","Clutch & Mini");
		categoryMap.put("0013-25","Crossbody");
		categoryMap.put("0013-28","Exotic");
		categoryMap.put("0013-18","Satchel");
		categoryMap.put("0013-16","Shoulder");
		categoryMap.put("0013-44","Small Leather Goods");
		categoryMap.put("0013-13","Tote");
		categoryMap.put("0022-2","Ballerinas");
		categoryMap.put("0022-15","Boat Shoes");
		categoryMap.put("0022-1","Boots");
		categoryMap.put("0022-20","Driver");
		categoryMap.put("0022-24","Espadrilles");
		categoryMap.put("0022-14","Evening");
		categoryMap.put("0022-22","Flats");
		categoryMap.put("0022-10","Loafers");
		categoryMap.put("0022-19","Mid-heel");
		categoryMap.put("0022-9","Monk Strap");
		categoryMap.put("0022-3","Mules");
		categoryMap.put("0022-11","Oxfords & Derby");
		categoryMap.put("0022-17","Platforms");
		categoryMap.put("0022-4","Pumps & Heels");
		categoryMap.put("0022-6","Sandals");
		categoryMap.put("0022-23","Sartorial");
		categoryMap.put("0022-7","Slides");
		categoryMap.put("0022-5","Slingbacks");
		categoryMap.put("0022-12","Sneakers");
		categoryMap.put("0022-8","Thongs");
		categoryMap.put("0022-18","T-strap");
		categoryMap.put("0022-13","Wedges");
		categoryMap.put("0022-16","Wingtips");
	}
	public Map<String, String> getCategoryMap() {
		return categoryMap;
	}
}
