// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `OpenApiServant.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Servant;

public interface _OpenApiServantOperations
{
    ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyIce[] FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopProductSkuIce[] FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopProductSkuPage FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.BaseDatas.SopCurrencyIce[] FindMoneyInfo(Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    java.util.Map<java.lang.String, java.lang.String> FindSuppliersById(String Id, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    java.util.Map<java.lang.String, java.lang.String> FindSuppliersByName(String Name, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrder(String supplierId, String returnOrderNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrder(String supplierId, String deliveryOrderNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SpCategoryPage FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SpBrandPage FindSpBrandPage(String supplierId, int pageIndex, int pageSize, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SpSizeTmpIce FindSpSizeTmp(String supplierId, String SizeTmpNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SpfProductAttributeInfoIce[] FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopAreaPage FindAreaPage(String supplierId, int pageIndex, int pageSize, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SpCategorySizeStandard[] FindSpCategorySizeStandard(String supplierId, String CategoryNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SpfProductMainColor[] FindSpfProductMainColor(String supplierId, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    int AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailSpecialPage FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.DirectoryPurchaseOrderDetailPage FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.DirectPurchaseOrder FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopProductPricePage FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderPage FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrder FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyPage FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryPage FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String PurchaseDetailError(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.BaseDatas.SopCategoryBrandAgreementPage FindCategoryBrandAgreementPage(String supplierId, ShangPin.SOP.Entity.Api.BaseDatas.SopCategoryBrandAgreementQuery query, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.DirectoryPurchaseOrderPage FindDirectoryPurchaseOrderPage(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DirectoryPurchaseOrderQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    java.util.List<java.lang.String> GetLogisticsCompany(String supplierId, String logisticsName, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean DirectUpdateStock(String supplierId, String SkuNo, String SupplierSkuNo, int InventoryQuantity, String PrewarningQuantity, String Freight, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Purchase.DirectPurchaseOrderApi FindDirectoryPurchaseOrder(String supplierId, String purchaseOrderNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean UpdateStockNew(String supplierId, String SkuNo, String SupplierSkuNo, int InventoryQuantity, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] FindDirectStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.List<java.lang.String> SupplierSkuNos, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String DeleteProduct(String supplierId, String SkuNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.DTO.PurchaseOrderInfoApiDto FindPurchaseOrderDetailCountPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String FindNetworkSpreadOrders(String appKey, String appSerect, String startDate, String endDate, String orderNo, String supplierOrderNo, String skuNo, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    boolean UpdateStockList(String supplierId, ShangPin.SOP.Entity.Api.Product.SopInventoryQuantityDto[] updateList, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    String AddSkuChangeMarketPriceMsg(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSkuChangeMarketPriceMsgEntity[] priceMsgList, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;

    ShangPin.SOP.Entity.Api.Supplier.SopInfoAPIEntity GetSupplierInfo(String supplierId, Ice.Current __current)
        throws ShangPin.SOP.Api.ApiException;
}
