// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `OpenApiServant.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Servant;

public interface OpenApiServantPrx extends Ice.ObjectPrx
{
    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyIce[] FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyIce[] FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, Callback_OpenApiServant_FindSupplyInfo __cb);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSupplyInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyIce[] end_FindSupplyInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Callback_OpenApiServant_UpdateSupplyPrice __cb);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx, Callback_OpenApiServant_UpdateSupplyPrice __cb);

    public boolean end_UpdateSupplyPrice(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, Callback_OpenApiServant_FindStockInfo __cb);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindStockInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] end_FindStockInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateStock(String supplierId, String SkuNo, int InventoryQuantity)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, Callback_OpenApiServant_UpdateStock __cb);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx, Callback_OpenApiServant_UpdateStock __cb);

    public boolean end_UpdateStock(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuIce[] FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuIce[] FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, Callback_OpenApiServant_FindCommodityInfo __cb);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindCommodityInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuIce[] end_FindCommodityInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuPage FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuPage FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, Callback_OpenApiServant_FindCommodityInfoPage __cb);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindCommodityInfoPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuPage end_FindCommodityInfoPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.BaseDatas.SopCurrencyIce[] FindMoneyInfo()
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.BaseDatas.SopCurrencyIce[] FindMoneyInfo(java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindMoneyInfo();

    public Ice.AsyncResult begin_FindMoneyInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindMoneyInfo(Ice.Callback __cb);

    public Ice.AsyncResult begin_FindMoneyInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindMoneyInfo(Callback_OpenApiServant_FindMoneyInfo __cb);

    public Ice.AsyncResult begin_FindMoneyInfo(java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindMoneyInfo __cb);

    public ShangPin.SOP.Entity.Api.BaseDatas.SopCurrencyIce[] end_FindMoneyInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersById(String Id)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersById(String Id, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSuppliersById(String Id);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, Callback_OpenApiServant_FindSuppliersById __cb);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSuppliersById __cb);

    public java.util.Map<java.lang.String, java.lang.String> end_FindSuppliersById(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersByName(String Name)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersByName(String Name, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSuppliersByName(String Name);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, Callback_OpenApiServant_FindSuppliersByName __cb);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSuppliersByName __cb);

    public java.util.Map<java.lang.String, java.lang.String> end_FindSuppliersByName(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public String CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder)
        throws ShangPin.SOP.Api.ApiException;

    public String CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, Ice.Callback __cb);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, Callback_OpenApiServant_CreateDeliveryOrder __cb);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx, Callback_OpenApiServant_CreateDeliveryOrder __cb);

    public String end_CreateDeliveryOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, Callback_OpenApiServant_AddPurchaseDetailToDeliveryOrder __cb);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx, Callback_OpenApiServant_AddPurchaseDetailToDeliveryOrder __cb);

    public boolean end_AddPurchaseDetailToDeliveryOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Callback_OpenApiServant_FindPurchaseOrderDetailPaged __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindPurchaseOrderDetailPaged __cb);

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage end_FindPurchaseOrderDetailPaged(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Callback_OpenApiServant_FindPurchaseOrderDetail __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindPurchaseOrderDetail __cb);

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage end_FindPurchaseOrderDetail(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, Callback_OpenApiServant_FindReturnOrderPaged __cb);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindReturnOrderPaged __cb);

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage end_FindReturnOrderPaged(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrder(String supplierId, String returnOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, Callback_OpenApiServant_FindReturnOrder __cb);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindReturnOrder __cb);

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage end_FindReturnOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, Callback_OpenApiServant_FindDeliveryOrderPaged __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDeliveryOrderPaged __cb);

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage end_FindDeliveryOrderPaged(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrder(String supplierId, String deliveryOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, Callback_OpenApiServant_FindDeliveryOrder __cb);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDeliveryOrder __cb);

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage end_FindDeliveryOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend)
        throws ShangPin.SOP.Api.ApiException;

    public boolean FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, Callback_OpenApiServant_FindDeliveryOrderSend __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDeliveryOrderSend __cb);

    public boolean end_FindDeliveryOrderSend(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategoryPage FindSpCategoryPage(String supplierId, int pageIndex, int pageSize)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategoryPage FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, Callback_OpenApiServant_FindSpCategoryPage __cb);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpCategoryPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SpCategoryPage end_FindSpCategoryPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpBrandPage FindSpBrandPage(String supplierId, int pageIndex, int pageSize)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpBrandPage FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, Callback_OpenApiServant_FindSpBrandPage __cb);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpBrandPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SpBrandPage end_FindSpBrandPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpSizeTmpIce FindSpSizeTmp(String supplierId, String SizeTmpNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpSizeTmpIce FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, Callback_OpenApiServant_FindSpSizeTmp __cb);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpSizeTmp __cb);

    public ShangPin.SOP.Entity.Api.Product.SpSizeTmpIce end_FindSpSizeTmp(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductAttributeInfoIce[] FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductAttributeInfoIce[] FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, Callback_OpenApiServant_FindSpSpfProductAttributeInfo __cb);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpSpfProductAttributeInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SpfProductAttributeInfoIce[] end_FindSpSpfProductAttributeInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopAreaPage FindAreaPage(String supplierId, int pageIndex, int pageSize)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopAreaPage FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, Callback_OpenApiServant_FindAreaPage __cb);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindAreaPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SopAreaPage end_FindAreaPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategorySizeStandard[] FindSpCategorySizeStandard(String supplierId, String CategoryNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategorySizeStandard[] FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, Callback_OpenApiServant_FindSpCategorySizeStandard __cb);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpCategorySizeStandard __cb);

    public ShangPin.SOP.Entity.Api.Product.SpCategorySizeStandard[] end_FindSpCategorySizeStandard(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductMainColor[] FindSpfProductMainColor(String supplierId)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductMainColor[] FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, Callback_OpenApiServant_FindSpfProductMainColor __cb);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpfProductMainColor __cb);

    public ShangPin.SOP.Entity.Api.Product.SpfProductMainColor[] end_FindSpfProductMainColor(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public int AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd)
        throws ShangPin.SOP.Api.ApiException;

    public int AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, Callback_OpenApiServant_AddCommodity __cb);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx, Callback_OpenApiServant_AddCommodity __cb);

    public int end_AddCommodity(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, Callback_OpenApiServant_AddCommodityPic __cb);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx, Callback_OpenApiServant_AddCommodityPic __cb);

    public boolean end_AddCommodityPic(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public String PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId)
        throws ShangPin.SOP.Api.ApiException;

    public String PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId);

    public Ice.AsyncResult begin_PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, Ice.Callback __cb);

    public Ice.AsyncResult begin_PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, Callback_OpenApiServant_PurchaseDetailEx __cb);

    public Ice.AsyncResult begin_PurchaseDetailEx(ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx purchaseOrderEx, String supplierId, java.util.Map<String, String> __ctx, Callback_OpenApiServant_PurchaseDetailEx __cb);

    public String end_PurchaseDetailEx(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public String FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo)
        throws ShangPin.SOP.Api.ApiException;

    public String FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo);

    public Ice.AsyncResult begin_FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo, Callback_OpenApiServant_FindCategoryBrandAgreement __cb);

    public Ice.AsyncResult begin_FindCategoryBrandAgreement(String supplierId, String categoryNo, String brandNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindCategoryBrandAgreement __cb);

    public String end_FindCategoryBrandAgreement(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price);

    public Ice.AsyncResult begin_UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Callback_OpenApiServant_UpdateSupplyPriceSpecial __cb);

    public Ice.AsyncResult begin_UpdateSupplyPriceSpecial(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx, Callback_OpenApiServant_UpdateSupplyPriceSpecial __cb);

    public boolean end_UpdateSupplyPriceSpecial(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailSpecialPage FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailSpecialPage FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo, Callback_OpenApiServant_FindPurchaseOrderDetailSpecial __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailSpecial(String supplierId, String purchaseOrderNo, String orderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindPurchaseOrderDetailSpecial __cb);

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailSpecialPage end_FindPurchaseOrderDetailSpecial(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DirectoryPurchaseOrderDetailPage FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DirectoryPurchaseOrderDetailPage FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Callback_OpenApiServant_FindDirectoryPurchaseOrderDetailPaged __cb);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDirectoryPurchaseOrderDetailPaged __cb);

    public ShangPin.SOP.Entity.Api.Purchase.DirectoryPurchaseOrderDetailPage end_FindDirectoryPurchaseOrderDetailPaged(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DirectPurchaseOrder FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DirectPurchaseOrder FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Callback_OpenApiServant_FindDirectoryPurchaseOrderDetail __cb);

    public Ice.AsyncResult begin_FindDirectoryPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDirectoryPurchaseOrderDetail __cb);

    public ShangPin.SOP.Entity.Api.Purchase.DirectPurchaseOrder end_FindDirectoryPurchaseOrderDetail(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public String SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder)
        throws ShangPin.SOP.Api.ApiException;

    public String SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder, Ice.Callback __cb);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder, Callback_OpenApiServant_SendDirectoryDeliveryOrder __cb);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SendDeliveryOrder sendDeliveryOrder, java.util.Map<String, String> __ctx, Callback_OpenApiServant_SendDirectoryDeliveryOrder __cb);

    public String end_SendDirectoryDeliveryOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public String SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx)
        throws ShangPin.SOP.Api.ApiException;

    public String SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx, Ice.Callback __cb);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx, Callback_OpenApiServant_SendDirectoryDeliveryOrderError __cb);

    public Ice.AsyncResult begin_SendDirectoryDeliveryOrderError(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderEx deliveryOrderEx, java.util.Map<String, String> __ctx, Callback_OpenApiServant_SendDirectoryDeliveryOrderError __cb);

    public String end_SendDirectoryDeliveryOrderError(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public String SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal)
        throws ShangPin.SOP.Api.ApiException;

    public String SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal);

    public Ice.AsyncResult begin_SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal, Ice.Callback __cb);

    public Ice.AsyncResult begin_SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal, Callback_OpenApiServant_SendArrivalAbnormalProcess __cb);

    public Ice.AsyncResult begin_SendArrivalAbnormalProcess(String supplierId, ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderAbnormal purchaseOrderAbnormal, java.util.Map<String, String> __ctx, Callback_OpenApiServant_SendArrivalAbnormalProcess __cb);

    public String end_SendArrivalAbnormalProcess(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductPricePage FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductPricePage FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto);

    public Ice.AsyncResult begin_FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto, Callback_OpenApiServant_FindProductPrice __cb);

    public Ice.AsyncResult begin_FindProductPrice(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindProductPrice __cb);

    public ShangPin.SOP.Entity.Api.Product.SopProductPricePage end_FindProductPrice(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice);

    public Ice.AsyncResult begin_UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice, Callback_OpenApiServant_UpdateProductPrice __cb);

    public Ice.AsyncResult begin_UpdateProductPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductPriceEditIce productPrice, java.util.Map<String, String> __ctx, Callback_OpenApiServant_UpdateProductPrice __cb);

    public boolean end_UpdateProductPrice(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderPage FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderPage FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto, Callback_OpenApiServant_FindSecondReturnOrderList __cb);

    public Ice.AsyncResult begin_FindSecondReturnOrderList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.SecondReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSecondReturnOrderList __cb);

    public ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderPage end_FindSecondReturnOrderList(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrder FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrder FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo);

    public Ice.AsyncResult begin_FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo, Callback_OpenApiServant_FindSecondReturnOrderByReturnNo __cb);

    public Ice.AsyncResult begin_FindSecondReturnOrderByReturnNo(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSecondReturnOrderByReturnNo __cb);

    public ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrder end_FindSecondReturnOrderByReturnNo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId)
        throws ShangPin.SOP.Api.ApiException;

    public boolean ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId);

    public Ice.AsyncResult begin_ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId, Ice.Callback __cb);

    public Ice.AsyncResult begin_ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId, Callback_OpenApiServant_ReceiveSecondReturnOrder __cb);

    public Ice.AsyncResult begin_ReceiveSecondReturnOrder(String supplierId, String returnOrderNo, String returnOrderDetailId, java.util.Map<String, String> __ctx, Callback_OpenApiServant_ReceiveSecondReturnOrder __cb);

    public boolean end_ReceiveSecondReturnOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail)
        throws ShangPin.SOP.Api.ApiException;

    public boolean SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail);

    public Ice.AsyncResult begin_SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail, Ice.Callback __cb);

    public Ice.AsyncResult begin_SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail, Callback_OpenApiServant_SubmitSecondReturnOrderAbnormal __cb);

    public Ice.AsyncResult begin_SubmitSecondReturnOrderAbnormal(String supplierId, ShangPin.SOP.Entity.Api.Purchase.SopSecondReturnOrderSupply secondReturnOrderDetail, java.util.Map<String, String> __ctx, Callback_OpenApiServant_SubmitSecondReturnOrderAbnormal __cb);

    public boolean end_SubmitSecondReturnOrderAbnormal(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyPage FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyPage FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply);

    public Ice.AsyncResult begin_FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply, Callback_OpenApiServant_FindSupplyInfoPage __cb);

    public Ice.AsyncResult begin_FindSupplyInfoPage(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.ProductPriceQueryDto supply, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSupplyInfoPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyPage end_FindSupplyInfoPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryPage FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryPage FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto);

    public Ice.AsyncResult begin_FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto, Callback_OpenApiServant_FindSopProductInventoryList __cb);

    public Ice.AsyncResult begin_FindSopProductInventoryList(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Product.SopSkuInventoryQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSopProductInventoryList __cb);

    public ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryPage end_FindSopProductInventoryList(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory)
        throws ShangPin.SOP.Api.ApiException;

    public boolean ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory);

    public Ice.AsyncResult begin_ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory, Ice.Callback __cb);

    public Ice.AsyncResult begin_ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory, Callback_OpenApiServant_ModifySkuInventoryQuantity __cb);

    public Ice.AsyncResult begin_ModifySkuInventoryQuantity(String supplierId, ShangPin.SOP.Entity.Api.Product.SopSupplierProductInventoryEditIce productInventory, java.util.Map<String, String> __ctx, Callback_OpenApiServant_ModifySkuInventoryQuantity __cb);

    public boolean end_ModifySkuInventoryQuantity(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic);

    public Ice.AsyncResult begin_AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic, Callback_OpenApiServant_AddSecondReturnOrderAbnormalPic __cb);

    public Ice.AsyncResult begin_AddSecondReturnOrderAbnormalPic(String supplierId, int detailId, byte[] sbnormalpic, java.util.Map<String, String> __ctx, Callback_OpenApiServant_AddSecondReturnOrderAbnormalPic __cb);

    public boolean end_AddSecondReturnOrderAbnormalPic(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;
}
