// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `OpenApiServant.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Servant;

public interface OpenApiServantPrx extends Ice.ObjectPrx
{
    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyIce[] FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyIce[] FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, Callback_OpenApiServant_FindSupplyInfo __cb);

    public Ice.AsyncResult begin_FindSupplyInfo(String supplierId, ShangPin.SOP.Entity.Api.Product.Supply supply, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSupplyInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SopSkuPriceApplyIce[] end_FindSupplyInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, Callback_OpenApiServant_UpdateSupplyPrice __cb);

    public Ice.AsyncResult begin_UpdateSupplyPrice(String supplierId, ShangPin.SOP.Entity.Api.Product.SupplyPriceInfo price, java.util.Map<String, String> __ctx, Callback_OpenApiServant_UpdateSupplyPrice __cb);

    public boolean end_UpdateSupplyPrice(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, Callback_OpenApiServant_FindStockInfo __cb);

    public Ice.AsyncResult begin_FindStockInfo(String supplierId, java.util.List<java.lang.String> SkuNos, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindStockInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SopSkuInventoryIce[] end_FindStockInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateStock(String supplierId, String SkuNo, int InventoryQuantity)
        throws ShangPin.SOP.Api.ApiException;

    public boolean UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, Callback_OpenApiServant_UpdateStock __cb);

    public Ice.AsyncResult begin_UpdateStock(String supplierId, String SkuNo, int InventoryQuantity, java.util.Map<String, String> __ctx, Callback_OpenApiServant_UpdateStock __cb);

    public boolean end_UpdateStock(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuIce[] FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuIce[] FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, Callback_OpenApiServant_FindCommodityInfo __cb);

    public Ice.AsyncResult begin_FindCommodityInfo(String supplierId, String Starttime, String Endtime, java.util.List<java.lang.String> ProductNos, java.util.List<java.lang.String> ProductModels, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindCommodityInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuIce[] end_FindCommodityInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuPage FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuPage FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, Callback_OpenApiServant_FindCommodityInfoPage __cb);

    public Ice.AsyncResult begin_FindCommodityInfoPage(String supplierId, ShangPin.SOP.Entity.Api.Product.SopProductSkuPageQuery query, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindCommodityInfoPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SopProductSkuPage end_FindCommodityInfoPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.BaseDatas.SopCurrencyIce[] FindMoneyInfo()
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.BaseDatas.SopCurrencyIce[] FindMoneyInfo(java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindMoneyInfo();

    public Ice.AsyncResult begin_FindMoneyInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindMoneyInfo(Ice.Callback __cb);

    public Ice.AsyncResult begin_FindMoneyInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindMoneyInfo(Callback_OpenApiServant_FindMoneyInfo __cb);

    public Ice.AsyncResult begin_FindMoneyInfo(java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindMoneyInfo __cb);

    public ShangPin.SOP.Entity.Api.BaseDatas.SopCurrencyIce[] end_FindMoneyInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersById(String Id)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersById(String Id, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSuppliersById(String Id);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, Callback_OpenApiServant_FindSuppliersById __cb);

    public Ice.AsyncResult begin_FindSuppliersById(String Id, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSuppliersById __cb);

    public java.util.Map<java.lang.String, java.lang.String> end_FindSuppliersById(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersByName(String Name)
        throws ShangPin.SOP.Api.ApiException;

    public java.util.Map<java.lang.String, java.lang.String> FindSuppliersByName(String Name, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSuppliersByName(String Name);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, Callback_OpenApiServant_FindSuppliersByName __cb);

    public Ice.AsyncResult begin_FindSuppliersByName(String Name, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSuppliersByName __cb);

    public java.util.Map<java.lang.String, java.lang.String> end_FindSuppliersByName(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public String CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder)
        throws ShangPin.SOP.Api.ApiException;

    public String CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, Ice.Callback __cb);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, Callback_OpenApiServant_CreateDeliveryOrder __cb);

    public Ice.AsyncResult begin_CreateDeliveryOrder(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderAdd deliverOrder, java.util.Map<String, String> __ctx, Callback_OpenApiServant_CreateDeliveryOrder __cb);

    public String end_CreateDeliveryOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, Callback_OpenApiServant_AddPurchaseDetailToDeliveryOrder __cb);

    public Ice.AsyncResult begin_AddPurchaseDetailToDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.List<java.lang.String> purchaseOrderDetailNos, java.util.Map<String, String> __ctx, Callback_OpenApiServant_AddPurchaseDetailToDeliveryOrder __cb);

    public boolean end_AddPurchaseDetailToDeliveryOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, Callback_OpenApiServant_FindPurchaseOrderDetailPaged __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetailPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.PurchaseOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindPurchaseOrderDetailPaged __cb);

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage end_FindPurchaseOrderDetailPaged(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, Callback_OpenApiServant_FindPurchaseOrderDetail __cb);

    public Ice.AsyncResult begin_FindPurchaseOrderDetail(String supplierId, String purchaseOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindPurchaseOrderDetail __cb);

    public ShangPin.SOP.Entity.Api.Purchase.PurchaseOrderDetailPage end_FindPurchaseOrderDetail(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, Callback_OpenApiServant_FindReturnOrderPaged __cb);

    public Ice.AsyncResult begin_FindReturnOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.ReturnOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindReturnOrderPaged __cb);

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage end_FindReturnOrderPaged(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrder(String supplierId, String returnOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, Callback_OpenApiServant_FindReturnOrder __cb);

    public Ice.AsyncResult begin_FindReturnOrder(String supplierId, String returnOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindReturnOrder __cb);

    public ShangPin.SOP.Entity.Api.Purchase.ReturnOrderPage end_FindReturnOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, Callback_OpenApiServant_FindDeliveryOrderPaged __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderPaged(String supplierId, ShangPin.SOP.Entity.Where.OpenApi.Purchase.DeliveryOrderQueryDto queryDto, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDeliveryOrderPaged __cb);

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage end_FindDeliveryOrderPaged(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrder(String supplierId, String deliveryOrderNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, Callback_OpenApiServant_FindDeliveryOrder __cb);

    public Ice.AsyncResult begin_FindDeliveryOrder(String supplierId, String deliveryOrderNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDeliveryOrder __cb);

    public ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderPage end_FindDeliveryOrder(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend)
        throws ShangPin.SOP.Api.ApiException;

    public boolean FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, Callback_OpenApiServant_FindDeliveryOrderSend __cb);

    public Ice.AsyncResult begin_FindDeliveryOrderSend(String supplierId, ShangPin.SOP.Entity.Api.Purchase.DeliveryOrderSend deliveryOrderSend, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindDeliveryOrderSend __cb);

    public boolean end_FindDeliveryOrderSend(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategoryPage FindSpCategoryPage(String supplierId, int pageIndex, int pageSize)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategoryPage FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, Callback_OpenApiServant_FindSpCategoryPage __cb);

    public Ice.AsyncResult begin_FindSpCategoryPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpCategoryPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SpCategoryPage end_FindSpCategoryPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpBrandPage FindSpBrandPage(String supplierId, int pageIndex, int pageSize)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpBrandPage FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, Callback_OpenApiServant_FindSpBrandPage __cb);

    public Ice.AsyncResult begin_FindSpBrandPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpBrandPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SpBrandPage end_FindSpBrandPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpSizeTmpIce FindSpSizeTmp(String supplierId, String SizeTmpNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpSizeTmpIce FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, Callback_OpenApiServant_FindSpSizeTmp __cb);

    public Ice.AsyncResult begin_FindSpSizeTmp(String supplierId, String SizeTmpNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpSizeTmp __cb);

    public ShangPin.SOP.Entity.Api.Product.SpSizeTmpIce end_FindSpSizeTmp(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductAttributeInfoIce[] FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductAttributeInfoIce[] FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, Callback_OpenApiServant_FindSpSpfProductAttributeInfo __cb);

    public Ice.AsyncResult begin_FindSpSpfProductAttributeInfo(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpSpfProductAttributeInfo __cb);

    public ShangPin.SOP.Entity.Api.Product.SpfProductAttributeInfoIce[] end_FindSpSpfProductAttributeInfo(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopAreaPage FindAreaPage(String supplierId, int pageIndex, int pageSize)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SopAreaPage FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, Callback_OpenApiServant_FindAreaPage __cb);

    public Ice.AsyncResult begin_FindAreaPage(String supplierId, int pageIndex, int pageSize, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindAreaPage __cb);

    public ShangPin.SOP.Entity.Api.Product.SopAreaPage end_FindAreaPage(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategorySizeStandard[] FindSpCategorySizeStandard(String supplierId, String CategoryNo)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpCategorySizeStandard[] FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, Callback_OpenApiServant_FindSpCategorySizeStandard __cb);

    public Ice.AsyncResult begin_FindSpCategorySizeStandard(String supplierId, String CategoryNo, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpCategorySizeStandard __cb);

    public ShangPin.SOP.Entity.Api.Product.SpCategorySizeStandard[] end_FindSpCategorySizeStandard(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductMainColor[] FindSpfProductMainColor(String supplierId)
        throws ShangPin.SOP.Api.ApiException;

    public ShangPin.SOP.Entity.Api.Product.SpfProductMainColor[] FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, Callback_OpenApiServant_FindSpfProductMainColor __cb);

    public Ice.AsyncResult begin_FindSpfProductMainColor(String supplierId, java.util.Map<String, String> __ctx, Callback_OpenApiServant_FindSpfProductMainColor __cb);

    public ShangPin.SOP.Entity.Api.Product.SpfProductMainColor[] end_FindSpfProductMainColor(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public int AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd)
        throws ShangPin.SOP.Api.ApiException;

    public int AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, Callback_OpenApiServant_AddCommodity __cb);

    public Ice.AsyncResult begin_AddCommodity(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductAddIce productAdd, java.util.Map<String, String> __ctx, Callback_OpenApiServant_AddCommodity __cb);

    public int end_AddCommodity(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce)
        throws ShangPin.SOP.Api.ApiException;

    public boolean AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx)
        throws ShangPin.SOP.Api.ApiException;

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, Callback_OpenApiServant_AddCommodityPic __cb);

    public Ice.AsyncResult begin_AddCommodityPic(String supplierId, ShangPin.SOP.Entity.Api.Product.ProductPicIce ProductPicIce, java.util.Map<String, String> __ctx, Callback_OpenApiServant_AddCommodityPic __cb);

    public boolean end_AddCommodityPic(Ice.AsyncResult __result)
        throws ShangPin.SOP.Api.ApiException;
}
