spring: 
  rabbitmq: 
           host: 192.168.20.175
           port: 5672
           username: scm-message-service
           password: scm-message-service
           virtual-host: /scm-message-service
  cloud: 
        stream: 
              bindings: 
                        spinnakerOriginalProduct: 
                              destination: spinnaker.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        ostoreOriginalProduct: 
                              destination: ostore.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        brunarossoOriginalProduct: 
                              destination: brunarosso.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        stefaniaOriginalProduct: 
                              destination: stefania.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        gebOriginalProduct: 
                              destination: geb.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        coltortiOriginalProduct: 
                              destination: coltorti.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        tonyOriginalProduct: 
                              destination: tony.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        biondioniOriginalProduct: 
                              destination: biondioni.original.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1                                                                                                                                                                                                                                                                                 
              rabbit: 
                      bindings: 
                            spinnakerOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            ostoreOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            brunarossoOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            stefaniaOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            gebOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            coltortiOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            tonyOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            biondioniOriginalProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false                                                                                                                                                                                                                                                                          
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
  mail: 
       default-recipient: yan_xiao_bin@126.com
       default-sender: yanxiaobin@shangpin.com
       default-encoding: UTF-8 # Default MimeMessage encoding.
       host: smtp.263.net # SMTP server host. For instance `smtp.example.com`
       port: 25 # SMTP server port.
       protocol: smtp # Protocol used by the SMTP server.
       username: yanxiaobin@shangpin.com # Login user of the SMTP server.
       password: 123.com # Login password of the SMTP server.
       test-connection: true # Test that the mail server is available on startup.
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       #image:
             #location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).