// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ProductPriceQueryDto.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Where.OpenApi.Product;

public final class ProductPriceQueryDtoPrxHelper extends Ice.ObjectPrxHelperBase implements ProductPriceQueryDtoPrx
{
    public static ProductPriceQueryDtoPrx checkedCast(Ice.ObjectPrx __obj)
    {
        ProductPriceQueryDtoPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof ProductPriceQueryDtoPrx)
            {
                __d = (ProductPriceQueryDtoPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    ProductPriceQueryDtoPrxHelper __h = new ProductPriceQueryDtoPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static ProductPriceQueryDtoPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        ProductPriceQueryDtoPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof ProductPriceQueryDtoPrx)
            {
                __d = (ProductPriceQueryDtoPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    ProductPriceQueryDtoPrxHelper __h = new ProductPriceQueryDtoPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static ProductPriceQueryDtoPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        ProductPriceQueryDtoPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    ProductPriceQueryDtoPrxHelper __h = new ProductPriceQueryDtoPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static ProductPriceQueryDtoPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        ProductPriceQueryDtoPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    ProductPriceQueryDtoPrxHelper __h = new ProductPriceQueryDtoPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static ProductPriceQueryDtoPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        ProductPriceQueryDtoPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof ProductPriceQueryDtoPrx)
            {
                __d = (ProductPriceQueryDtoPrx)__obj;
            }
            else
            {
                ProductPriceQueryDtoPrxHelper __h = new ProductPriceQueryDtoPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static ProductPriceQueryDtoPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        ProductPriceQueryDtoPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            ProductPriceQueryDtoPrxHelper __h = new ProductPriceQueryDtoPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Where::OpenApi::Product::ProductPriceQueryDto"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _ProductPriceQueryDtoDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _ProductPriceQueryDtoDelD();
    }

    public static void __write(IceInternal.BasicStream __os, ProductPriceQueryDtoPrx v)
    {
        __os.writeProxy(v);
    }

    public static ProductPriceQueryDtoPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ProductPriceQueryDtoPrxHelper result = new ProductPriceQueryDtoPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
