feign.hystrix.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
spring: 
  rabbitmq: 
           host: 192.168.20.175
           port: 5672
           username: ephub-message-service-qa
           password: ephub-message-service-qa
           virtual-host: /ephub-message-service-qa
  cloud: 
        consul: 
          host: localhost
          port: 8500
          discovery: 
            prefer-agent-address: true
            prefer-ip-address: true
            health-check-interval: 15s
            health-check-timeout: 15s
            register: true
            register-health-check: true
        stream:
            bindings:
                      supplierRetryPrice:
                            destination: retry.product.price
                            content-type: application/json
                      supplierProducerPrice:
                             destination: supplier.product.price
                             content-type: application/json
                      supplierPrice:
                            destination: supplier.product.price
                            group: one
                            consumer:
                                     concurrency: 4
                                     maxAttempts: 1
                      retrySupplierPrice:
                            destination: retry.product.price
                            group: one
                            consumer:
                                     concurrency: 4
                                     maxAttempts: 1
            rabbit:
                    bindings:
                          supplierRetryPrice:
                                producer:
                                     prefix: HA.
                          supplierProducerPrice:
                                producer:
                                     prefix: HA.
                          supplierPrice:
                                consumer:
                                     prefix: HA.
                                     autoBindDlq: false
                                     requeueRejected: true
                                     republishToDlq: false
                          retrySupplierPrice:
                                consumer:
                                     prefix: HA.
                                     autoBindDlq: false
                                     requeueRejected: true
                                     republishToDlq: false
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8       
  mail: 
       default-recipient: yan_xiao_bin@126.com
       default-sender: yanxiaobin@shangpin.com
       default-encoding: UTF-8
       host: smtp.263.net
       port: 25
       protocol: smtp
       username: yanxiaobin@shangpin.com
       password: 123.com
       test-connection: false
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).
shangpin: 
       certificate: 
             usernameAndPassword: 
                  2016030701799: 
                      username: shangpin
                      password: Shang2016
                  2016083001937: 
                      username: shangpin
                      password: Shang1808
                  2016011201731: 
                      username: shangpin
                      password: Atelier2015
                  2016012101751:                                     
                      username: shangpin
                      password: Atelier2015
