feign.hystrix.enabled: false
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
spring: 
  rabbitmq: 
           host: 172.20.11.49
           port: 5672
           username: ephub-message-service
           password: ephub-message-service
           virtual-host: /ephub-message-service
  cloud: 
        consul: 
          host: localhost
          port: 8500
          discovery: 
            prefer-agent-address: true
            prefer-ip-address: true
            health-check-interval: 90s
            health-check-timeout: 60s
            register: true
            register-health-check: true
        stream:
            bindings:
                      supplierRetryPrice:
                            destination: retry.product.price
                            content-type: application/json
                      supplierProducerPrice:
                             destination: supplier.product.price
                             content-type: application/json
                      supplierPrice:
                            destination: supplier.product.price
                            group: one
                            consumer:
                                     concurrency: 4
                                     maxAttempts: 1
                      retrySupplierPrice:
                            destination: retry.product.price
                            group: one
                            consumer:
                                     concurrency: 4
                                     maxAttempts: 1
            rabbit:
                    bindings:
                          supplierRetryPrice:
                                producer:
                                     prefix: HA.
                          supplierProducerPrice:
                                producer:
                                     prefix: HA.
                          supplierPrice:
                                consumer:
                                     prefix: HA.
                                     autoBindDlq: false
                                     requeueRejected: true
                                     republishToDlq: false
                          retrySupplierPrice:
                                consumer:
                                     prefix: HA.
                                     autoBindDlq: false
                                     requeueRejected: true
                                     republishToDlq: false
  jackson:
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8       
  mail: 
       default-recipient: lizhongren@shangpin.com
       default-sender: chengxu@shangpin.com
       default-encoding: UTF-8 # Default MimeMessage encoding.
       host: smtp.shangpin.com # SMTP server host. For instance `smtp.example.com`
       port: 25 # SMTP server port.
       protocol: smtp # Protocol used by the SMTP server.
       username: chengxu@shangpin.com # Login user of the SMTP server.
       password: shangpin001 # Login password of the SMTP server.
       test-connection: false # Test that the mail server is available on startup.
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).
shangpin:
   hub:
       callAddress:
              gmsAddProductUrl: http://scmapi.spidc1.com/gms/Product/AddProduct
              gmsSizeUrl: http://scmapi.spidc1.com/gms/ProductBasicData/GetProductSize
              gmsBrandUrl: http://scmapi.spidc1.com/gms/ProductBasicData/GetBrands
              gmsCategoryUrl: http://scmapi.spidc1.com/gms/ProductBasicData/GetCategory
              scmsSupplierInfoUrl: http://scm.shangpin.com/scms/Supplier/GetSupplierInfoListByNo?supplierNo=
              sopSkuListBySupplierSkuNoUrl: http://sopoutapi.spidc1.com/Product/GetSopSkuListBySupplierSkuNo