spring: 
  data: 
      mongodb: 
             uri: mongodb://192.168.9.135:27017/order-stock-message-service
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image: 
             location: classpath:banner/yan.png # Banner image file location (jpg/png can also be used).