spring: 
  cloud: 
       consul: 
         host: 192.168.20.235
         port: 8500
         discovery: 
           prefer-agent-address: true
           prefer-ip-address: true
           health-check-interval: 10s
           health-check-timeout: 10s           
           register: true
           register-health-check: true
  data: 
       mongodb: 
           uri: mongodb://192.168.9.135:27017/ephub-data-mongodb-service
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image: 
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).