
package lcvmagws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-26T11:39:49.917+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class LcvMagWSSOAPPortType_LcvMagWSSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:LcvMagWS", "LcvMagWS");

    private LcvMagWSSOAPPortType_LcvMagWSSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
    	
        URL wsdlURL = LcvMagWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LcvMagWS ss = new LcvMagWS(wsdlURL, SERVICE_NAME);
        LcvMagWSSOAPPortType port = ss.getLcvMagWSSOAPPort();  
        System.out.println("Invoking lectureTarifWeb...");
        java.lang.String _lectureTarifWeb_sArticle = "1800501";
        java.lang.String _lectureTarifWeb_bCData = "20140201";
        java.lang.String _lectureTarifWeb_sUser = "BION456";
        java.lang.String _lectureTarifWeb_sMdp = "INI123 ";
        java.lang.String _lectureTarifWeb__return = port.lectureTarifWeb(_lectureTarifWeb_sArticle, _lectureTarifWeb_bCData, _lectureTarifWeb_sUser, _lectureTarifWeb_sMdp);
        System.out.println("lectureTarifWeb.result=" + _lectureTarifWeb__return);

        {
        	
        	
        	
        	
        System.out.println("Invoking ecritureClient...");
        java.lang.String _ecritureClient_sEmail = "";
        java.lang.String _ecritureClient_sNomCli = "";
        java.lang.String _ecritureClient_sPrenomCli = "";
        java.lang.String _ecritureClient_sAdr1 = "";
        java.lang.String _ecritureClient_sAdr2 = "";
        java.lang.String _ecritureClient_sCP = "";
        java.lang.String _ecritureClient_sVille = "";
        java.lang.String _ecritureClient_sCodePays = "";
        java.lang.String _ecritureClient_sMdPInternet = "";
        java.lang.String _ecritureClient_sSociete = "";
        java.lang.String _ecritureClient_sNumTVA = "";
        java.lang.String _ecritureClient_sTel = "";
        java.lang.String _ecritureClient_sAdrLivr = "";
        java.lang.String _ecritureClient_sDateNaissance = "";
        java.lang.String _ecritureClient_sCodeCli = "";
        java.lang.String _ecritureClient_sCodeSite = "";
        java.lang.String _ecritureClient_sUser = "";
        java.lang.String _ecritureClient_sMdp = "";
        java.lang.String _ecritureClient_sCiv = "";
        java.lang.String _ecritureClient_sTypClient = "";
        java.lang.String _ecritureClient__return = port.ecritureClient(_ecritureClient_sEmail, _ecritureClient_sNomCli, _ecritureClient_sPrenomCli, _ecritureClient_sAdr1, _ecritureClient_sAdr2, _ecritureClient_sCP, _ecritureClient_sVille, _ecritureClient_sCodePays, _ecritureClient_sMdPInternet, _ecritureClient_sSociete, _ecritureClient_sNumTVA, _ecritureClient_sTel, _ecritureClient_sAdrLivr, _ecritureClient_sDateNaissance, _ecritureClient_sCodeCli, _ecritureClient_sCodeSite, _ecritureClient_sUser, _ecritureClient_sMdp, _ecritureClient_sCiv, _ecritureClient_sTypClient);
        System.out.println("ecritureClient.result=" + _ecritureClient__return);


        }
        {
        System.out.println("Invoking lectureStockParMag...");
        java.lang.String _lectureStockParMag_sArticle = "";
        java.lang.String _lectureStockParMag_bCData = "";
        java.lang.String _lectureStockParMag_sUser = "";
        java.lang.String _lectureStockParMag_sMdp = "";
        java.lang.String _lectureStockParMag_sMagInternet = "";
        java.lang.String _lectureStockParMag__return = port.lectureStockParMag(_lectureStockParMag_sArticle, _lectureStockParMag_bCData, _lectureStockParMag_sUser, _lectureStockParMag_sMdp, _lectureStockParMag_sMagInternet);
        System.out.println("lectureStockParMag.result=" + _lectureStockParMag__return);


        }
        {
        System.out.println("Invoking lectureDesModelesGarant...");
        java.lang.String _lectureDesModelesGarant_sAdherent = "";
        java.lang.String _lectureDesModelesGarant_sUser = "";
        java.lang.String _lectureDesModelesGarant_sMdp = "";
        java.lang.String _lectureDesModelesGarant__return = port.lectureDesModelesGarant(_lectureDesModelesGarant_sAdherent, _lectureDesModelesGarant_sUser, _lectureDesModelesGarant_sMdp);
        System.out.println("lectureDesModelesGarant.result=" + _lectureDesModelesGarant__return);


        }
        {
        System.out.println("Invoking lectureCBLCV...");
        java.lang.String _lectureCBLCV_sCodeArticle = "";
        java.lang.String _lectureCBLCV_sTaille = "";
        java.lang.String _lectureCBLCV_sUser = "";
        java.lang.String _lectureCBLCV_sMdp = "";
        java.lang.String _lectureCBLCV__return = port.lectureCBLCV(_lectureCBLCV_sCodeArticle, _lectureCBLCV_sTaille, _lectureCBLCV_sUser, _lectureCBLCV_sMdp);
        System.out.println("lectureCBLCV.result=" + _lectureCBLCV__return);


        }
        {
        System.out.println("Invoking ecritureVenteGesCom...");
        java.lang.String _ecritureVenteGesCom_sVente = "";
        java.lang.String _ecritureVenteGesCom_sCodeCli = "";
        java.lang.String _ecritureVenteGesCom_sCodeMag = "";
        java.lang.String _ecritureVenteGesCom_sCodeSite = "";
        java.lang.String _ecritureVenteGesCom_sCodeRepresentant = "";
        java.lang.String _ecritureVenteGesCom_sCodReglt = "";
        java.lang.String _ecritureVenteGesCom_sCodePromo = "";
        java.lang.String _ecritureVenteGesCom_bCoordonees = "";
        java.lang.String _ecritureVenteGesCom_sAdrsLivr = "";
        java.lang.String _ecritureVenteGesCom_sUser = "";
        java.lang.String _ecritureVenteGesCom_sMdp = "";
        java.lang.String _ecritureVenteGesCom_sCommentaire = "";
        java.lang.String _ecritureVenteGesCom__return = port.ecritureVenteGesCom(_ecritureVenteGesCom_sVente, _ecritureVenteGesCom_sCodeCli, _ecritureVenteGesCom_sCodeMag, _ecritureVenteGesCom_sCodeSite, _ecritureVenteGesCom_sCodeRepresentant, _ecritureVenteGesCom_sCodReglt, _ecritureVenteGesCom_sCodePromo, _ecritureVenteGesCom_bCoordonees, _ecritureVenteGesCom_sAdrsLivr, _ecritureVenteGesCom_sUser, _ecritureVenteGesCom_sMdp, _ecritureVenteGesCom_sCommentaire);
        System.out.println("ecritureVenteGesCom.result=" + _ecritureVenteGesCom__return);


        }
        {
        System.out.println("Invoking lectureStockParMagSurCde...");
        java.lang.String _lectureStockParMagSurCde_sArticle = "";
        java.lang.String _lectureStockParMagSurCde_bCData = "";
        java.lang.String _lectureStockParMagSurCde_sUser = "";
        java.lang.String _lectureStockParMagSurCde_sMdp = "";
        java.lang.String _lectureStockParMagSurCde_sMagInternet = "";
        java.lang.String _lectureStockParMagSurCde__return = port.lectureStockParMagSurCde(_lectureStockParMagSurCde_sArticle, _lectureStockParMagSurCde_bCData, _lectureStockParMagSurCde_sUser, _lectureStockParMagSurCde_sMdp, _lectureStockParMagSurCde_sMagInternet);
        System.out.println("lectureStockParMagSurCde.result=" + _lectureStockParMagSurCde__return);


        }
        {
        System.out.println("Invoking connexionClient...");
        java.lang.String _connexionClient_sMailCli = "";
        java.lang.String _connexionClient_sMdpCli = "";
        java.lang.String _connexionClient_sUser = "";
        java.lang.String _connexionClient_sMdp = "";
        java.lang.String _connexionClient__return = port.connexionClient(_connexionClient_sMailCli, _connexionClient_sMdpCli, _connexionClient_sUser, _connexionClient_sMdp);
        System.out.println("connexionClient.result=" + _connexionClient__return);


        }
        {
        System.out.println("Invoking lectureDetailCdeGesCom...");
        java.lang.String _lectureDetailCdeGesCom_sNumCde = "";
        java.lang.String _lectureDetailCdeGesCom_sCodeCli = "";
        java.lang.String _lectureDetailCdeGesCom_bCData = "";
        java.lang.String _lectureDetailCdeGesCom_sUser = "";
        java.lang.String _lectureDetailCdeGesCom_sMdp = "";
        java.lang.String _lectureDetailCdeGesCom__return = port.lectureDetailCdeGesCom(_lectureDetailCdeGesCom_sNumCde, _lectureDetailCdeGesCom_sCodeCli, _lectureDetailCdeGesCom_bCData, _lectureDetailCdeGesCom_sUser, _lectureDetailCdeGesCom_sMdp);
        System.out.println("lectureDetailCdeGesCom.result=" + _lectureDetailCdeGesCom__return);


        }
        {
        System.out.println("Invoking ecritureTransfertArriveeTransit...");
        java.lang.String _ecritureTransfertArriveeTransit_sNumTrf = "";
        java.lang.String _ecritureTransfertArriveeTransit_sLstArticle = "";
        java.lang.String _ecritureTransfertArriveeTransit_sUser = "";
        java.lang.String _ecritureTransfertArriveeTransit_sMdp = "";
        java.lang.String _ecritureTransfertArriveeTransit__return = port.ecritureTransfertArriveeTransit(_ecritureTransfertArriveeTransit_sNumTrf, _ecritureTransfertArriveeTransit_sLstArticle, _ecritureTransfertArriveeTransit_sUser, _ecritureTransfertArriveeTransit_sMdp);
        System.out.println("ecritureTransfertArriveeTransit.result=" + _ecritureTransfertArriveeTransit__return);


        }
        {


        }
        {
        System.out.println("Invoking annulationTransfert...");
        java.lang.String _annulationTransfert_sNumTrf = "";
        java.lang.String _annulationTransfert_sUser = "";
        java.lang.String _annulationTransfert_sMdp = "";
        java.lang.String _annulationTransfert__return = port.annulationTransfert(_annulationTransfert_sNumTrf, _annulationTransfert_sUser, _annulationTransfert_sMdp);
        System.out.println("annulationTransfert.result=" + _annulationTransfert__return);


        }
        {
        System.out.println("Invoking lecturePromo...");
        java.lang.String _lecturePromo_sVente = "";
        java.lang.String _lecturePromo_sCodePromo = "";
        java.lang.String _lecturePromo_sCodeCli = "";
        java.lang.String _lecturePromo_sUser = "";
        java.lang.String _lecturePromo_sMdp = "";
        java.lang.String _lecturePromo__return = port.lecturePromo(_lecturePromo_sVente, _lecturePromo_sCodePromo, _lecturePromo_sCodeCli, _lecturePromo_sUser, _lecturePromo_sMdp);
        System.out.println("lecturePromo.result=" + _lecturePromo__return);


        }
        {
        System.out.println("Invoking ecritureVenteSKU...");
        java.lang.String _ecritureVenteSKU_sVente = "";
        java.lang.String _ecritureVenteSKU_sEncaissement = "";
        java.lang.String _ecritureVenteSKU_sTVA = "";
        java.lang.String _ecritureVenteSKU_sMagasin = "";
        java.lang.String _ecritureVenteSKU_sDate = "";
        java.lang.String _ecritureVenteSKU_scodeCli = "";
        java.lang.String _ecritureVenteSKU_sUser = "";
        java.lang.String _ecritureVenteSKU_sMdp = "";
        java.lang.String _ecritureVenteSKU__return = port.ecritureVenteSKU(_ecritureVenteSKU_sVente, _ecritureVenteSKU_sEncaissement, _ecritureVenteSKU_sTVA, _ecritureVenteSKU_sMagasin, _ecritureVenteSKU_sDate, _ecritureVenteSKU_scodeCli, _ecritureVenteSKU_sUser, _ecritureVenteSKU_sMdp);
        System.out.println("ecritureVenteSKU.result=" + _ecritureVenteSKU__return);


        }
        {
        System.out.println("Invoking lectureDesModelesAvecPrix...");
        java.lang.String _lectureDesModelesAvecPrix_bCData = "";
        java.lang.String _lectureDesModelesAvecPrix_sDateModif = "";
        java.lang.String _lectureDesModelesAvecPrix_sUser = "";
        java.lang.String _lectureDesModelesAvecPrix_sMdp = "";
        java.lang.String _lectureDesModelesAvecPrix__return = port.lectureDesModelesAvecPrix(_lectureDesModelesAvecPrix_bCData, _lectureDesModelesAvecPrix_sDateModif, _lectureDesModelesAvecPrix_sUser, _lectureDesModelesAvecPrix_sMdp);
        System.out.println("lectureDesModelesAvecPrix.result=" + _lectureDesModelesAvecPrix__return);


        }
        {
        System.out.println("Invoking ecritureTransfertDepartTransit...");
        java.lang.String _ecritureTransfertDepartTransit_sMagD = "";
        java.lang.String _ecritureTransfertDepartTransit_sMagA = "";
        java.lang.String _ecritureTransfertDepartTransit_sLstArticle = "";
        java.lang.String _ecritureTransfertDepartTransit_sUser = "";
        java.lang.String _ecritureTransfertDepartTransit_sMdp = "";
        java.lang.String _ecritureTransfertDepartTransit__return = port.ecritureTransfertDepartTransit(_ecritureTransfertDepartTransit_sMagD, _ecritureTransfertDepartTransit_sMagA, _ecritureTransfertDepartTransit_sLstArticle, _ecritureTransfertDepartTransit_sUser, _ecritureTransfertDepartTransit_sMdp);
        System.out.println("ecritureTransfertDepartTransit.result=" + _ecritureTransfertDepartTransit__return);


        }
        {
        System.out.println("Invoking lectureCdeGesCom...");
        java.lang.String _lectureCdeGesCom_sCodeCli = "";
        java.lang.String _lectureCdeGesCom_bCData = "";
        java.lang.String _lectureCdeGesCom_sUser = "";
        java.lang.String _lectureCdeGesCom_sMdp = "";
        java.lang.String _lectureCdeGesCom__return = port.lectureCdeGesCom(_lectureCdeGesCom_sCodeCli, _lectureCdeGesCom_bCData, _lectureCdeGesCom_sUser, _lectureCdeGesCom_sMdp);
        System.out.println("lectureCdeGesCom.result=" + _lectureCdeGesCom__return);


        }
        {
        System.out.println("Invoking lectureStockParMag1...");
        java.lang.String _lectureStockParMag1_sArticle = "";
        java.lang.String _lectureStockParMag1_bCData = "";
        java.lang.String _lectureStockParMag1_sUser = "";
        java.lang.String _lectureStockParMag1_sMdp = "";
        java.lang.String _lectureStockParMag1_sMagInternet = "";
        java.lang.String _lectureStockParMag1__return = port.lectureStockParMag1(_lectureStockParMag1_sArticle, _lectureStockParMag1_bCData, _lectureStockParMag1_sUser, _lectureStockParMag1_sMdp, _lectureStockParMag1_sMagInternet);
        System.out.println("lectureStockParMag1.result=" + _lectureStockParMag1__return);


        }
        {
        System.out.println("Invoking lectureClient...");
        java.lang.String _lectureClient_sCodeCli = "";
        java.lang.String _lectureClient_bCData = "";
        java.lang.String _lectureClient_sUser = "";
        java.lang.String _lectureClient_sMdp = "";
        java.lang.String _lectureClient__return = port.lectureClient(_lectureClient_sCodeCli, _lectureClient_bCData, _lectureClient_sUser, _lectureClient_sMdp);
        System.out.println("lectureClient.result=" + _lectureClient__return);


        }
        {
        System.out.println("Invoking lectureDesModeles...");
        java.lang.String _lectureDesModeles_bCData = "";
        java.lang.String _lectureDesModeles_sDateModif = "";
        java.lang.String _lectureDesModeles_sUser = "";
        java.lang.String _lectureDesModeles_sMdp = "";
        java.lang.String _lectureDesModeles__return = port.lectureDesModeles(_lectureDesModeles_bCData, _lectureDesModeles_sDateModif, _lectureDesModeles_sUser, _lectureDesModeles_sMdp);
        System.out.println("lectureDesModeles.result=" + _lectureDesModeles__return);


        }
        {
        System.out.println("Invoking ecritureVente...");
        java.lang.String _ecritureVente_sVente = "";
        java.lang.String _ecritureVente_sCodeCli = "";
        java.lang.String _ecritureVente_sUser = "";
        java.lang.String _ecritureVente_sMdp = "";
        java.lang.String _ecritureVente__return = port.ecritureVente(_ecritureVente_sVente, _ecritureVente_sCodeCli, _ecritureVente_sUser, _ecritureVente_sMdp);
        System.out.println("ecritureVente.result=" + _ecritureVente__return);


        }
        {
        System.out.println("Invoking lecturePLA...");
        java.lang.String _lecturePLA_bCData = "";
        java.lang.String _lecturePLA_sUser = "";
        java.lang.String _lecturePLA_sMdp = "";
        java.lang.String _lecturePLA__return = port.lecturePLA(_lecturePLA_bCData, _lecturePLA_sUser, _lecturePLA_sMdp);
        System.out.println("lecturePLA.result=" + _lecturePLA__return);


        }
        {
        System.out.println("Invoking lectureDesTables...");
        java.lang.String _lectureDesTables_bCData = "";
        java.lang.String _lectureDesTables_sUser = "";
        java.lang.String _lectureDesTables_sMdp = "";
        java.lang.String _lectureDesTables__return = port.lectureDesTables(_lectureDesTables_bCData, _lectureDesTables_sUser, _lectureDesTables_sMdp);
        System.out.println("lectureDesTables.result=" + _lectureDesTables__return);


        }
        {
        System.out.println("Invoking lectureDuStock...");
        java.lang.String _lectureDuStock_sArticle = "";
        java.lang.String _lectureDuStock_bCData = "";
        java.lang.String _lectureDuStock_sUser = "";
        java.lang.String _lectureDuStock_sMdp = "";
        java.lang.String _lectureDuStock__return = port.lectureDuStock(_lectureDuStock_sArticle, _lectureDuStock_bCData, _lectureDuStock_sUser, _lectureDuStock_sMdp);
        System.out.println("lectureDuStock.result=" + _lectureDuStock__return);


        }
        {
        System.out.println("Invoking lectureDuStock1...");
        java.lang.String _lectureDuStock1_sArticle = "";
        java.lang.String _lectureDuStock1_bCData = "";
        java.lang.String _lectureDuStock1_sUser = "";
        java.lang.String _lectureDuStock1_sMdp = "";
        java.lang.String _lectureDuStock1__return = port.lectureDuStock1(_lectureDuStock1_sArticle, _lectureDuStock1_bCData, _lectureDuStock1_sUser, _lectureDuStock1_sMdp);
        System.out.println("lectureDuStock1.result=" + _lectureDuStock1__return);


        }
        {
        System.out.println("Invoking motdePassePerdu...");
        java.lang.String _motdePassePerdu_sMailCli = "";
        java.lang.String _motdePassePerdu_bCData = "";
        java.lang.String _motdePassePerdu_sUser = "";
        java.lang.String _motdePassePerdu_sMdp = "";
        java.lang.String _motdePassePerdu__return = port.motdePassePerdu(_motdePassePerdu_sMailCli, _motdePassePerdu_bCData, _motdePassePerdu_sUser, _motdePassePerdu_sMdp);
        System.out.println("motdePassePerdu.result=" + _motdePassePerdu__return);


        }
        {
        System.out.println("Invoking ecritureTransfertDepartDirect...");
        java.lang.String _ecritureTransfertDepartDirect_sMagD = "";
        java.lang.String _ecritureTransfertDepartDirect_sMagA = "";
        java.lang.String _ecritureTransfertDepartDirect_sLstArticle = "";
        java.lang.String _ecritureTransfertDepartDirect_sUser = "";
        java.lang.String _ecritureTransfertDepartDirect_sMdp = "";
        java.lang.String _ecritureTransfertDepartDirect__return = port.ecritureTransfertDepartDirect(_ecritureTransfertDepartDirect_sMagD, _ecritureTransfertDepartDirect_sMagA, _ecritureTransfertDepartDirect_sLstArticle, _ecritureTransfertDepartDirect_sUser, _ecritureTransfertDepartDirect_sMdp);
        System.out.println("ecritureTransfertDepartDirect.result=" + _ecritureTransfertDepartDirect__return);


        }
        {
        System.out.println("Invoking testEmailClient...");
        java.lang.String _testEmailClient_sMailCli = "";
        java.lang.String _testEmailClient_bCData = "";
        java.lang.String _testEmailClient_sUser = "";
        java.lang.String _testEmailClient_sMdp = "";
        java.lang.String _testEmailClient__return = port.testEmailClient(_testEmailClient_sMailCli, _testEmailClient_bCData, _testEmailClient_sUser, _testEmailClient_sMdp);
        System.out.println("testEmailClient.result=" + _testEmailClient__return);


        }
        {
        System.out.println("Invoking ecritureRetourSKU...");
        java.lang.String _ecritureRetourSKU_sVente = "";
        java.lang.String _ecritureRetourSKU_sEncaissement = "";
        java.lang.String _ecritureRetourSKU_sTVA = "";
        java.lang.String _ecritureRetourSKU_sMagasin = "";
        java.lang.String _ecritureRetourSKU_sDate = "";
        java.lang.String _ecritureRetourSKU_scodeCli = "";
        java.lang.String _ecritureRetourSKU_sUser = "";
        java.lang.String _ecritureRetourSKU_sMdp = "";
        java.lang.String _ecritureRetourSKU__return = port.ecritureRetourSKU(_ecritureRetourSKU_sVente, _ecritureRetourSKU_sEncaissement, _ecritureRetourSKU_sTVA, _ecritureRetourSKU_sMagasin, _ecritureRetourSKU_sDate, _ecritureRetourSKU_scodeCli, _ecritureRetourSKU_sUser, _ecritureRetourSKU_sMdp);
        System.out.println("ecritureRetourSKU.result=" + _ecritureRetourSKU__return);


        }

        System.exit(0);
    }

}
