
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package lcvmagws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-26T11:57:41.454+08:00
 * Generated source version: 3.1.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "LcvMagWS",
                      portName = "LcvMagWSSOAPPort",
                      targetNamespace = "urn:LcvMagWS",
                      wsdlLocation = "http://80.12.82.220:8080/LCVMAGWS_WEB/awws/LcvMagWS.awws?wsdl",
                      endpointInterface = "lcvmagws.LcvMagWSSOAPPortType")
                      
public class LcvMagWSSOAPPortImpl implements LcvMagWSSOAPPortType {

    private static final Logger LOG = Logger.getLogger(LcvMagWSSOAPPortImpl.class.getName());

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureClient(java.lang.String  sEmail ,)java.lang.String  sNomCli ,)java.lang.String  sPrenomCli ,)java.lang.String  sAdr1 ,)java.lang.String  sAdr2 ,)java.lang.String  sCP ,)java.lang.String  sVille ,)java.lang.String  sCodePays ,)java.lang.String  sMdPInternet ,)java.lang.String  sSociete ,)java.lang.String  sNumTVA ,)java.lang.String  sTel ,)java.lang.String  sAdrLivr ,)java.lang.String  sDateNaissance ,)java.lang.String  sCodeCli ,)java.lang.String  sCodeSite ,)java.lang.String  sUser ,)java.lang.String  sMdp ,)java.lang.String  sCiv ,)java.lang.String  sTypClient )*
     */
    public java.lang.String ecritureClient(java.lang.String sEmail,java.lang.String sNomCli,java.lang.String sPrenomCli,java.lang.String sAdr1,java.lang.String sAdr2,java.lang.String sCP,java.lang.String sVille,java.lang.String sCodePays,java.lang.String sMdPInternet,java.lang.String sSociete,java.lang.String sNumTVA,java.lang.String sTel,java.lang.String sAdrLivr,java.lang.String sDateNaissance,java.lang.String sCodeCli,java.lang.String sCodeSite,java.lang.String sUser,java.lang.String sMdp,java.lang.String sCiv,java.lang.String sTypClient) { 
        LOG.info("Executing operation ecritureClient");
        System.out.println(sEmail);
        System.out.println(sNomCli);
        System.out.println(sPrenomCli);
        System.out.println(sAdr1);
        System.out.println(sAdr2);
        System.out.println(sCP);
        System.out.println(sVille);
        System.out.println(sCodePays);
        System.out.println(sMdPInternet);
        System.out.println(sSociete);
        System.out.println(sNumTVA);
        System.out.println(sTel);
        System.out.println(sAdrLivr);
        System.out.println(sDateNaissance);
        System.out.println(sCodeCli);
        System.out.println(sCodeSite);
        System.out.println(sUser);
        System.out.println(sMdp);
        System.out.println(sCiv);
        System.out.println(sTypClient);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureStockParMag(java.lang.String  sArticle ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp ,)java.lang.String  sMagInternet )*
     */
    public java.lang.String lectureStockParMag(java.lang.String sArticle,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp,java.lang.String sMagInternet) { 
        LOG.info("Executing operation lectureStockParMag");
        System.out.println(sArticle);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        System.out.println(sMagInternet);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureDesModelesGarant(java.lang.String  sAdherent ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureDesModelesGarant(java.lang.String sAdherent,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureDesModelesGarant");
        System.out.println(sAdherent);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureCBLCV(java.lang.String  sCodeArticle ,)java.lang.String  sTaille ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureCBLCV(java.lang.String sCodeArticle,java.lang.String sTaille,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureCBLCV");
        System.out.println(sCodeArticle);
        System.out.println(sTaille);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureVenteGesCom(java.lang.String  sVente ,)java.lang.String  sCodeCli ,)java.lang.String  sCodeMag ,)java.lang.String  sCodeSite ,)java.lang.String  sCodeRepresentant ,)java.lang.String  sCodReglt ,)java.lang.String  sCodePromo ,)java.lang.String  bCoordonees ,)java.lang.String  sAdrsLivr ,)java.lang.String  sUser ,)java.lang.String  sMdp ,)java.lang.String  sCommentaire )*
     */
    public java.lang.String ecritureVenteGesCom(java.lang.String sVente,java.lang.String sCodeCli,java.lang.String sCodeMag,java.lang.String sCodeSite,java.lang.String sCodeRepresentant,java.lang.String sCodReglt,java.lang.String sCodePromo,java.lang.String bCoordonees,java.lang.String sAdrsLivr,java.lang.String sUser,java.lang.String sMdp,java.lang.String sCommentaire) { 
        LOG.info("Executing operation ecritureVenteGesCom");
        System.out.println(sVente);
        System.out.println(sCodeCli);
        System.out.println(sCodeMag);
        System.out.println(sCodeSite);
        System.out.println(sCodeRepresentant);
        System.out.println(sCodReglt);
        System.out.println(sCodePromo);
        System.out.println(bCoordonees);
        System.out.println(sAdrsLivr);
        System.out.println(sUser);
        System.out.println(sMdp);
        System.out.println(sCommentaire);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureStockParMagSurCde(java.lang.String  sArticle ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp ,)java.lang.String  sMagInternet )*
     */
    public java.lang.String lectureStockParMagSurCde(java.lang.String sArticle,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp,java.lang.String sMagInternet) { 
        LOG.info("Executing operation lectureStockParMagSurCde");
        System.out.println(sArticle);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        System.out.println(sMagInternet);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#connexionClient(java.lang.String  sMailCli ,)java.lang.String  sMdpCli ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String connexionClient(java.lang.String sMailCli,java.lang.String sMdpCli,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation connexionClient");
        System.out.println(sMailCli);
        System.out.println(sMdpCli);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureDetailCdeGesCom(java.lang.String  sNumCde ,)java.lang.String  sCodeCli ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureDetailCdeGesCom(java.lang.String sNumCde,java.lang.String sCodeCli,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureDetailCdeGesCom");
        System.out.println(sNumCde);
        System.out.println(sCodeCli);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureTransfertArriveeTransit(java.lang.String  sNumTrf ,)java.lang.String  sLstArticle ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String ecritureTransfertArriveeTransit(java.lang.String sNumTrf,java.lang.String sLstArticle,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation ecritureTransfertArriveeTransit");
        System.out.println(sNumTrf);
        System.out.println(sLstArticle);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureTarifWeb(java.lang.String  sArticle ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureTarifWeb(java.lang.String sArticle,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureTarifWeb");
        System.out.println(sArticle);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#annulationTransfert(java.lang.String  sNumTrf ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String annulationTransfert(java.lang.String sNumTrf,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation annulationTransfert");
        System.out.println(sNumTrf);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lecturePromo(java.lang.String  sVente ,)java.lang.String  sCodePromo ,)java.lang.String  sCodeCli ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lecturePromo(java.lang.String sVente,java.lang.String sCodePromo,java.lang.String sCodeCli,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lecturePromo");
        System.out.println(sVente);
        System.out.println(sCodePromo);
        System.out.println(sCodeCli);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureVenteSKU(java.lang.String  sVente ,)java.lang.String  sEncaissement ,)java.lang.String  sTVA ,)java.lang.String  sMagasin ,)java.lang.String  sDate ,)java.lang.String  scodeCli ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String ecritureVenteSKU(java.lang.String sVente,java.lang.String sEncaissement,java.lang.String sTVA,java.lang.String sMagasin,java.lang.String sDate,java.lang.String scodeCli,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation ecritureVenteSKU");
        System.out.println(sVente);
        System.out.println(sEncaissement);
        System.out.println(sTVA);
        System.out.println(sMagasin);
        System.out.println(sDate);
        System.out.println(scodeCli);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureDesModelesAvecPrix(java.lang.String  bCData ,)java.lang.String  sDateModif ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureDesModelesAvecPrix(java.lang.String bCData,java.lang.String sDateModif,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureDesModelesAvecPrix");
        System.out.println(bCData);
        System.out.println(sDateModif);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureTransfertDepartTransit(java.lang.String  sMagD ,)java.lang.String  sMagA ,)java.lang.String  sLstArticle ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String ecritureTransfertDepartTransit(java.lang.String sMagD,java.lang.String sMagA,java.lang.String sLstArticle,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation ecritureTransfertDepartTransit");
        System.out.println(sMagD);
        System.out.println(sMagA);
        System.out.println(sLstArticle);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureCdeGesCom(java.lang.String  sCodeCli ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureCdeGesCom(java.lang.String sCodeCli,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureCdeGesCom");
        System.out.println(sCodeCli);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureStockParMag1(java.lang.String  sArticle ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp ,)java.lang.String  sMagInternet )*
     */
    public java.lang.String lectureStockParMag1(java.lang.String sArticle,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp,java.lang.String sMagInternet) { 
        LOG.info("Executing operation lectureStockParMag1");
        System.out.println(sArticle);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        System.out.println(sMagInternet);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureClient(java.lang.String  sCodeCli ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureClient(java.lang.String sCodeCli,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureClient");
        System.out.println(sCodeCli);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureDesModeles(java.lang.String  bCData ,)java.lang.String  sDateModif ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureDesModeles(java.lang.String bCData,java.lang.String sDateModif,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureDesModeles");
        System.out.println(bCData);
        System.out.println(sDateModif);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureVente(java.lang.String  sVente ,)java.lang.String  sCodeCli ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String ecritureVente(java.lang.String sVente,java.lang.String sCodeCli,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation ecritureVente");
        System.out.println(sVente);
        System.out.println(sCodeCli);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lecturePLA(java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lecturePLA(java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lecturePLA");
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureDesTables(java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureDesTables(java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureDesTables");
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureDuStock(java.lang.String  sArticle ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureDuStock(java.lang.String sArticle,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureDuStock");
        System.out.println(sArticle);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#lectureDuStock1(java.lang.String  sArticle ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String lectureDuStock1(java.lang.String sArticle,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation lectureDuStock1");
        System.out.println(sArticle);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#motdePassePerdu(java.lang.String  sMailCli ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String motdePassePerdu(java.lang.String sMailCli,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation motdePassePerdu");
        System.out.println(sMailCli);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureTransfertDepartDirect(java.lang.String  sMagD ,)java.lang.String  sMagA ,)java.lang.String  sLstArticle ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String ecritureTransfertDepartDirect(java.lang.String sMagD,java.lang.String sMagA,java.lang.String sLstArticle,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation ecritureTransfertDepartDirect");
        System.out.println(sMagD);
        System.out.println(sMagA);
        System.out.println(sLstArticle);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#testEmailClient(java.lang.String  sMailCli ,)java.lang.String  bCData ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String testEmailClient(java.lang.String sMailCli,java.lang.String bCData,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation testEmailClient");
        System.out.println(sMailCli);
        System.out.println(bCData);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see lcvmagws.LcvMagWSSOAPPortType#ecritureRetourSKU(java.lang.String  sVente ,)java.lang.String  sEncaissement ,)java.lang.String  sTVA ,)java.lang.String  sMagasin ,)java.lang.String  sDate ,)java.lang.String  scodeCli ,)java.lang.String  sUser ,)java.lang.String  sMdp )*
     */
    public java.lang.String ecritureRetourSKU(java.lang.String sVente,java.lang.String sEncaissement,java.lang.String sTVA,java.lang.String sMagasin,java.lang.String sDate,java.lang.String scodeCli,java.lang.String sUser,java.lang.String sMdp) { 
        LOG.info("Executing operation ecritureRetourSKU");
        System.out.println(sVente);
        System.out.println(sEncaissement);
        System.out.println(sTVA);
        System.out.println(sMagasin);
        System.out.println(sDate);
        System.out.println(scodeCli);
        System.out.println(sUser);
        System.out.println(sMdp);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
