// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `DeliveryOrderSend.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Purchase;

public class DeliveryOrderSend extends Ice.ObjectImpl
{
    public DeliveryOrderSend()
    {
    }

    public DeliveryOrderSend(String SopDeliveryOrderNo, String LogisticsName, String LogisticsOrderNo, String DateDeliver, String EstimateArrivedTime, String DeliveryContacts, String DeliveryContactsPhone, String DeliveryAddress, String DeliveryMemo)
    {
        this.SopDeliveryOrderNo = SopDeliveryOrderNo;
        this.LogisticsName = LogisticsName;
        this.LogisticsOrderNo = LogisticsOrderNo;
        this.DateDeliver = DateDeliver;
        this.EstimateArrivedTime = EstimateArrivedTime;
        this.DeliveryContacts = DeliveryContacts;
        this.DeliveryContactsPhone = DeliveryContactsPhone;
        this.DeliveryAddress = DeliveryAddress;
        this.DeliveryMemo = DeliveryMemo;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new DeliveryOrderSend();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Purchase::DeliveryOrderSend"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.writeString(SopDeliveryOrderNo);
        __os.writeString(LogisticsName);
        __os.writeString(LogisticsOrderNo);
        __os.writeString(DateDeliver);
        __os.writeString(EstimateArrivedTime);
        __os.writeString(DeliveryContacts);
        __os.writeString(DeliveryContactsPhone);
        __os.writeString(DeliveryAddress);
        __os.writeString(DeliveryMemo);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        SopDeliveryOrderNo = __is.readString();
        LogisticsName = __is.readString();
        LogisticsOrderNo = __is.readString();
        DateDeliver = __is.readString();
        EstimateArrivedTime = __is.readString();
        DeliveryContacts = __is.readString();
        DeliveryContactsPhone = __is.readString();
        DeliveryAddress = __is.readString();
        DeliveryMemo = __is.readString();
        __is.endReadSlice();
    }

    public String SopDeliveryOrderNo;

    public String LogisticsName;

    public String LogisticsOrderNo;

    public String DateDeliver;

    public String EstimateArrivedTime;

    public String DeliveryContacts;

    public String DeliveryContactsPhone;

    public String DeliveryAddress;

    public String DeliveryMemo;

    public static final long serialVersionUID = -335332510L;
}
