// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `DirectoryPurchaseOrderPage.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Purchase;

public final class DirectoryPurchaseOrderPagePrxHelper extends Ice.ObjectPrxHelperBase implements DirectoryPurchaseOrderPagePrx
{
    public static DirectoryPurchaseOrderPagePrx checkedCast(Ice.ObjectPrx __obj)
    {
        DirectoryPurchaseOrderPagePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DirectoryPurchaseOrderPagePrx)
            {
                __d = (DirectoryPurchaseOrderPagePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DirectoryPurchaseOrderPagePrxHelper __h = new DirectoryPurchaseOrderPagePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DirectoryPurchaseOrderPagePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DirectoryPurchaseOrderPagePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DirectoryPurchaseOrderPagePrx)
            {
                __d = (DirectoryPurchaseOrderPagePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DirectoryPurchaseOrderPagePrxHelper __h = new DirectoryPurchaseOrderPagePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DirectoryPurchaseOrderPagePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DirectoryPurchaseOrderPagePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DirectoryPurchaseOrderPagePrxHelper __h = new DirectoryPurchaseOrderPagePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DirectoryPurchaseOrderPagePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DirectoryPurchaseOrderPagePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DirectoryPurchaseOrderPagePrxHelper __h = new DirectoryPurchaseOrderPagePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DirectoryPurchaseOrderPagePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        DirectoryPurchaseOrderPagePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DirectoryPurchaseOrderPagePrx)
            {
                __d = (DirectoryPurchaseOrderPagePrx)__obj;
            }
            else
            {
                DirectoryPurchaseOrderPagePrxHelper __h = new DirectoryPurchaseOrderPagePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DirectoryPurchaseOrderPagePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DirectoryPurchaseOrderPagePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DirectoryPurchaseOrderPagePrxHelper __h = new DirectoryPurchaseOrderPagePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Purchase::DirectoryPurchaseOrderPage"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _DirectoryPurchaseOrderPageDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _DirectoryPurchaseOrderPageDelD();
    }

    public static void __write(IceInternal.BasicStream __os, DirectoryPurchaseOrderPagePrx v)
    {
        __os.writeProxy(v);
    }

    public static DirectoryPurchaseOrderPagePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DirectoryPurchaseOrderPagePrxHelper result = new DirectoryPurchaseOrderPagePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
