// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `DirectoryPurchaseOrderPage.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Purchase;

public class DirectPurchaseOrderDetailApi extends Ice.ObjectImpl
{
    public DirectPurchaseOrderDetailApi()
    {
    }

    public DirectPurchaseOrderDetailApi(String SopPurchaseOrderDetailNo, String SopPurchaseOrderNo, String SkuNo, String SupplierSkuNo, int DetailStatus, String WarehouseNo, String SkuPrice, String SkuPriceCurrency, String ConsigneeName, String ConsigneeAddress, String ConsigneeMobile, String Freight, String FreightCurrency)
    {
        this.SopPurchaseOrderDetailNo = SopPurchaseOrderDetailNo;
        this.SopPurchaseOrderNo = SopPurchaseOrderNo;
        this.SkuNo = SkuNo;
        this.SupplierSkuNo = SupplierSkuNo;
        this.DetailStatus = DetailStatus;
        this.WarehouseNo = WarehouseNo;
        this.SkuPrice = SkuPrice;
        this.SkuPriceCurrency = SkuPriceCurrency;
        this.ConsigneeName = ConsigneeName;
        this.ConsigneeAddress = ConsigneeAddress;
        this.ConsigneeMobile = ConsigneeMobile;
        this.Freight = Freight;
        this.FreightCurrency = FreightCurrency;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new DirectPurchaseOrderDetailApi();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Purchase::DirectPurchaseOrderDetailApi"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.writeString(SopPurchaseOrderDetailNo);
        __os.writeString(SopPurchaseOrderNo);
        __os.writeString(SkuNo);
        __os.writeString(SupplierSkuNo);
        __os.writeInt(DetailStatus);
        __os.writeString(WarehouseNo);
        __os.writeString(SkuPrice);
        __os.writeString(SkuPriceCurrency);
        __os.writeString(ConsigneeName);
        __os.writeString(ConsigneeAddress);
        __os.writeString(ConsigneeMobile);
        __os.writeString(Freight);
        __os.writeString(FreightCurrency);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        SopPurchaseOrderDetailNo = __is.readString();
        SopPurchaseOrderNo = __is.readString();
        SkuNo = __is.readString();
        SupplierSkuNo = __is.readString();
        DetailStatus = __is.readInt();
        WarehouseNo = __is.readString();
        SkuPrice = __is.readString();
        SkuPriceCurrency = __is.readString();
        ConsigneeName = __is.readString();
        ConsigneeAddress = __is.readString();
        ConsigneeMobile = __is.readString();
        Freight = __is.readString();
        FreightCurrency = __is.readString();
        __is.endReadSlice();
    }

    public String SopPurchaseOrderDetailNo;

    public String SopPurchaseOrderNo;

    public String SkuNo;

    public String SupplierSkuNo;

    public int DetailStatus;

    public String WarehouseNo;

    public String SkuPrice;

    public String SkuPriceCurrency;

    public String ConsigneeName;

    public String ConsigneeAddress;

    public String ConsigneeMobile;

    public String Freight;

    public String FreightCurrency;

    public static final long serialVersionUID = 406468883L;
}
