// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `DirectoryPurchaseOrderPage.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Purchase;

public class DirectPurchaseOrderApi extends Ice.ObjectImpl
{
    public DirectPurchaseOrderApi()
    {
    }

    public DirectPurchaseOrderApi(String SopPurchaseOrderNo, String SupplierNo, String DateStart, String DateEnd, String Memo, java.util.List<DirectPurchaseOrderDetailApi> DirectPurchaseOrderDetailList, int IsOutside, String LogisticsName, String LogisticsOrderNo, String CreateTime, String DeliveryAddress, String DeliveryContacts, String DeliveryContactsPhone, String DeliveryMemo, String EstimateArrivedTime, String TotalAmount, int TotalQuantity, String Freight, String FreightCurrency)
    {
        this.SopPurchaseOrderNo = SopPurchaseOrderNo;
        this.SupplierNo = SupplierNo;
        this.DateStart = DateStart;
        this.DateEnd = DateEnd;
        this.Memo = Memo;
        this.DirectPurchaseOrderDetailList = DirectPurchaseOrderDetailList;
        this.IsOutside = IsOutside;
        this.LogisticsName = LogisticsName;
        this.LogisticsOrderNo = LogisticsOrderNo;
        this.CreateTime = CreateTime;
        this.DeliveryAddress = DeliveryAddress;
        this.DeliveryContacts = DeliveryContacts;
        this.DeliveryContactsPhone = DeliveryContactsPhone;
        this.DeliveryMemo = DeliveryMemo;
        this.EstimateArrivedTime = EstimateArrivedTime;
        this.TotalAmount = TotalAmount;
        this.TotalQuantity = TotalQuantity;
        this.Freight = Freight;
        this.FreightCurrency = FreightCurrency;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new DirectPurchaseOrderApi();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Purchase::DirectPurchaseOrderApi"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.writeString(SopPurchaseOrderNo);
        __os.writeString(SupplierNo);
        __os.writeString(DateStart);
        __os.writeString(DateEnd);
        __os.writeString(Memo);
        DirectPurchaseOrderDetailApiListHelper.write(__os, DirectPurchaseOrderDetailList);
        __os.writeInt(IsOutside);
        __os.writeString(LogisticsName);
        __os.writeString(LogisticsOrderNo);
        __os.writeString(CreateTime);
        __os.writeString(DeliveryAddress);
        __os.writeString(DeliveryContacts);
        __os.writeString(DeliveryContactsPhone);
        __os.writeString(DeliveryMemo);
        __os.writeString(EstimateArrivedTime);
        __os.writeString(TotalAmount);
        __os.writeInt(TotalQuantity);
        __os.writeString(Freight);
        __os.writeString(FreightCurrency);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        SopPurchaseOrderNo = __is.readString();
        SupplierNo = __is.readString();
        DateStart = __is.readString();
        DateEnd = __is.readString();
        Memo = __is.readString();
        DirectPurchaseOrderDetailList = DirectPurchaseOrderDetailApiListHelper.read(__is);
        IsOutside = __is.readInt();
        LogisticsName = __is.readString();
        LogisticsOrderNo = __is.readString();
        CreateTime = __is.readString();
        DeliveryAddress = __is.readString();
        DeliveryContacts = __is.readString();
        DeliveryContactsPhone = __is.readString();
        DeliveryMemo = __is.readString();
        EstimateArrivedTime = __is.readString();
        TotalAmount = __is.readString();
        TotalQuantity = __is.readInt();
        Freight = __is.readString();
        FreightCurrency = __is.readString();
        __is.endReadSlice();
    }

    public String SopPurchaseOrderNo;

    public String SupplierNo;

    public String DateStart;

    public String DateEnd;

    public String Memo;

    public java.util.List<DirectPurchaseOrderDetailApi> DirectPurchaseOrderDetailList;

    public int IsOutside;

    public String LogisticsName;

    public String LogisticsOrderNo;

    public String CreateTime;

    public String DeliveryAddress;

    public String DeliveryContacts;

    public String DeliveryContactsPhone;

    public String DeliveryMemo;

    public String EstimateArrivedTime;

    public String TotalAmount;

    public int TotalQuantity;

    public String Freight;

    public String FreightCurrency;

    public static final long serialVersionUID = -2063479297L;
}
