// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SendDeliveryOrder.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Purchase;

public class SendDeliveryOrder extends Ice.ObjectImpl
{
    public SendDeliveryOrder()
    {
    }

    public SendDeliveryOrder(String PurchaseOrderNo, String PurchaseOrderDetailNos, long SopDeliveryOrderNo, String LogisticsName, String LogisticsOrderNo, int DeliveryCount, int PurchaseOrderCount, int ProductCount, byte PrintStatus, String DateDeliver, int EstimateArrivedTime, String DateArrival, int DeliveryStatus, String DeliveryContacts, String DeliveryContactsPhone, String DeliveryAddress, String DeliveryMemo, String SaleAmount, String SettlementCurrencyName)
    {
        this.PurchaseOrderNo = PurchaseOrderNo;
        this.PurchaseOrderDetailNos = PurchaseOrderDetailNos;
        this.SopDeliveryOrderNo = SopDeliveryOrderNo;
        this.LogisticsName = LogisticsName;
        this.LogisticsOrderNo = LogisticsOrderNo;
        this.DeliveryCount = DeliveryCount;
        this.PurchaseOrderCount = PurchaseOrderCount;
        this.ProductCount = ProductCount;
        this.PrintStatus = PrintStatus;
        this.DateDeliver = DateDeliver;
        this.EstimateArrivedTime = EstimateArrivedTime;
        this.DateArrival = DateArrival;
        this.DeliveryStatus = DeliveryStatus;
        this.DeliveryContacts = DeliveryContacts;
        this.DeliveryContactsPhone = DeliveryContactsPhone;
        this.DeliveryAddress = DeliveryAddress;
        this.DeliveryMemo = DeliveryMemo;
        this.SaleAmount = SaleAmount;
        this.SettlementCurrencyName = SettlementCurrencyName;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new SendDeliveryOrder();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::ShangPin::SOP::Entity::Api::Purchase::SendDeliveryOrder"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, true);
        __os.writeString(PurchaseOrderNo);
        __os.writeString(PurchaseOrderDetailNos);
        __os.writeLong(SopDeliveryOrderNo);
        __os.writeString(LogisticsName);
        __os.writeString(LogisticsOrderNo);
        __os.writeInt(DeliveryCount);
        __os.writeInt(PurchaseOrderCount);
        __os.writeInt(ProductCount);
        __os.writeByte(PrintStatus);
        __os.writeString(DateDeliver);
        __os.writeInt(EstimateArrivedTime);
        __os.writeString(DateArrival);
        __os.writeInt(DeliveryStatus);
        __os.writeString(DeliveryContacts);
        __os.writeString(DeliveryContactsPhone);
        __os.writeString(DeliveryAddress);
        __os.writeString(DeliveryMemo);
        __os.writeString(SaleAmount);
        __os.writeString(SettlementCurrencyName);
        __os.endWriteSlice();
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        PurchaseOrderNo = __is.readString();
        PurchaseOrderDetailNos = __is.readString();
        SopDeliveryOrderNo = __is.readLong();
        LogisticsName = __is.readString();
        LogisticsOrderNo = __is.readString();
        DeliveryCount = __is.readInt();
        PurchaseOrderCount = __is.readInt();
        ProductCount = __is.readInt();
        PrintStatus = __is.readByte();
        DateDeliver = __is.readString();
        EstimateArrivedTime = __is.readInt();
        DateArrival = __is.readString();
        DeliveryStatus = __is.readInt();
        DeliveryContacts = __is.readString();
        DeliveryContactsPhone = __is.readString();
        DeliveryAddress = __is.readString();
        DeliveryMemo = __is.readString();
        SaleAmount = __is.readString();
        SettlementCurrencyName = __is.readString();
        __is.endReadSlice();
    }

    public String PurchaseOrderNo;

    public String PurchaseOrderDetailNos;

    public long SopDeliveryOrderNo;

    public String LogisticsName;

    public String LogisticsOrderNo;

    public int DeliveryCount;

    public int PurchaseOrderCount;

    public int ProductCount;

    public byte PrintStatus;

    public String DateDeliver;

    public int EstimateArrivedTime;

    public String DateArrival;

    public int DeliveryStatus;

    public String DeliveryContacts;

    public String DeliveryContactsPhone;

    public String DeliveryAddress;

    public String DeliveryMemo;

    public String SaleAmount;

    public String SettlementCurrencyName;

    public static final long serialVersionUID = -1399421439L;
}
