// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SopSecondReturnOrderPage.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ShangPin.SOP.Entity.Api.Purchase;

public final class SopSecondReturnOrderPageHolder extends Ice.ObjectHolderBase<SopSecondReturnOrderPage>
{
    public
    SopSecondReturnOrderPageHolder()
    {
    }

    public
    SopSecondReturnOrderPageHolder(SopSecondReturnOrderPage value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof SopSecondReturnOrderPage)
        {
            value = (SopSecondReturnOrderPage)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return SopSecondReturnOrderPage.ice_staticId();
    }
}
