feign.hystrix.enabled: false
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
spring: 
  rabbitmq: 
           host: ${rabbitmq.host:172.20.11.49}
           port: 5672
           username: ephub-message-service
           password: ephub-message-service
           virtual-host: /ephub-message-service
  cloud: 
        consul: 
          host: localhost
          port: 8500
          discovery: 
            prefer-agent-address: true
            prefer-ip-address: true
            health-check-interval: 15s
            health-check-timeout: 15s            
            register: true
            register-health-check: true
        stream: 
              bindings: 
                        supplierRetryPictureProduct: 
                              destination: retry.product.picture
                              content-type: application/json              
                        supplierPictureProduct: 
                              destination: supplier.product.picture
                              group: one
                              consumer: 
                                       concurrency: 3
                                       maxAttempts: 1
                        brandPictureProduct: 
                              destination: brand.product.picture
                              group: one
                              consumer: 
                                       concurrency: 3
                                       maxAttempts: 1
                        retryPictureProduct: 
                              destination: retry.product.picture
                              group: one
                              consumer: 
                                       concurrency: 2
                                       maxAttempts: 1
                        retryBrandPictureProduct: 
                              destination: retry.brand.product.picture
                              group: one
                              consumer: 
                                       concurrency: 1
                                       maxAttempts: 1
                        stefaniamodePictureProduct: 
                              destination: stefaniamode.product.picture
                              group: one
                              consumer: 
                                       concurrency: 1
                                       maxAttempts: 1
                        mclablesPictureProduct:
                              destination: mclables.product.picture
                              group: one
                              consumer:
                                        concurrency: 3
                                        maxAttempts: 1
                        eraldoPictureProduct:
                              destination: eraldo.product.picture
                              group: one
                              consumer:
                                        concurrency: 3
                                        maxAttempts: 1
                        frmodaPictureProduct:
                              destination: frmoda.product.picture
                              group: one
                              consumer:
                                        concurrency: 3
                                        maxAttempts: 1
                        reebonzPictureProduct:
                              destination: reebonz.product.picture
                              group: one
                              consumer:
                                        concurrency: 3
                                        maxAttempts: 1
              rabbit: 
                      bindings: 
                            supplierRetryPictureProduct: 
                                  producer: 
                                       prefix: HA.                      
                            supplierPictureProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            brandPictureProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false 
                            retryPictureProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            retryBrandPictureProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            stefaniamodePictureProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            mclablesPictureProduct:
                                  consumer:
                                        prefix: HA.
                                        autoBindDlq: false
                                        requeueRejected: true
                                        republishToDlq: false
                            eraldoPictureProduct:
                                  consumer:
                                        prefix: HA.
                                        autoBindDlq: false
                                        requeueRejected: true
                                        republishToDlq: false
                            frmodaPictureProduct:
                                  consumer:
                                        prefix: HA.
                                        autoBindDlq: false
                                        requeueRejected: true
                                        republishToDlq: false
                            reebonzPictureProduct:
                                  consumer:
                                        prefix: HA.
                                        autoBindDlq: false
                                        requeueRejected: true
                                        republishToDlq: false
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8       
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used).
shangpin: 
       certificate: 
             usernameAndPassword: 
                  2016030701799: 
                      username: shangpin
                      password: Shang2016
                  2016083001937: 
                      username: shangpin
                      password: Shang1808
                  2016011201731: 
                      username: shangpin
                      password: Atelier2015
                  2016012101751:                                     
                      username: shangpin
                      password: Atelier2015  
                  2015112001671: 
                      username: mosuftp
                      password: inter2015£
                  2016110101955:
                      username: Shangpin
                      password: Shangpin17!
                  2018091702058:
                      username: account219383@dylog.it
                      password: Account1111
       brandSupplierIds: 2018070502014,
