spring: 
  rabbitmq: 
           host: 192.168.20.175
           port: 5672
           username: scm-message-service
           password: scm-message-service
           virtual-host: /scm-message-service
  cloud: 
        stream: 
              bindings: 
                        spinnakerPendingProduct: 
                              destination: spinnaker.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        ostorePendingProduct: 
                              destination: ostore.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        brunarossoPendingProduct: 
                              destination: brunarosso.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        stefaniaPendingProduct: 
                              destination: stefania.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        gebPendingProduct: 
                              destination: geb.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        coltortiPendingProduct: 
                              destination: coltorti.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        tonyPendingProduct: 
                              destination: tony.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1
                        biondioniPendingProduct: 
                              destination: biondioni.pending.product
                              group: one
                              consumer: 
                                       concurrency: 5
                                       maxAttempts: 1                                                                                                                                                                                                                                                                                 
              rabbit: 
                      bindings: 
                            spinnakerPendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            ostorePendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            brunarossoPendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            stefaniaPendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            gebPendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            coltortiPendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            tonyPendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false
                            biondioniPendingProduct: 
                                  consumer: 
                                       prefix: HA.
                                       autoBindDlq: false
                                       requeueRejected: true
                                       republishToDlq: false                                                                                                                                                                                                                                                                          
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
       time-zone: GMT+8       
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image:
             location: classpath:banner/logo.jpg # Banner image file location (jpg/png can also be used)
shangpin: 
       certificate: 
             usernameAndPassword: 
                  2016030701799: 
                      username: shangpin
                      password: Shang2016
                  2016083001937: 
                      username: shangpin
                      password: Shang1808
                  2016011201731: 
                      username: shangpin
                      password: Atelier2015
                  2016012101751:                                     
                      username: shangpin
                      password: Atelier2015              