server.port: 8000
spring:
  rabbitmq: 
           host: 192.168.20.175
           port: 5672
           username: scm-message-service
           password: scm-message-service
           virtual-host: /scm-message-service
  cloud: 
        stream: 
              bindings: 
                        spinnakerOriginalProduct: 
                              destination: spinnaker.original.product
                              content-type: application/json
                        ostoreOriginalProduct: 
                              destination: ostore.original.product
                              content-type: application/json
                        brunarossoOriginalProduct: 
                              destination: brunarosso.original.product
                              content-type: application/json
                        stefaniaOriginalProduct: 
                              destination: stefania.original.product
                              content-type: application/json
                        gebOriginalProduct: 
                              destination: geb.original.product
                              content-type: application/json
                        coltortiOriginalProduct: 
                              destination: coltorti.original.product
                              content-type: application/json
                        tonyOriginalProduct: 
                              destination: tony.original.product
                              content-type: application/json
                        biondioniOriginalProduct: 
                              destination: biondioni.original.product
                              content-type: application/json                                                                                                                                                                                                              
              rabbit: 
                      bindings: 
                            spinnakerOriginalProduct: 
                                  producer: 
                                           prefix: HA.
                            ostoreOriginalProduct: 
                                  producer: 
                                           prefix: HA.
                            brunarossoOriginalProduct: 
                                  producer: 
                                           prefix: HA.
                            stefaniaOriginalProduct: 
                                  producer: 
                                           prefix: HA.
                            gebOriginalProduct: 
                                  producer: 
                                           prefix: HA.
                            coltortiOriginalProduct: 
                                  producer: 
                                           prefix: HA.
                            tonyOriginalProduct: 
                                  producer: 
                                           prefix: HA. 
                            biondioniOriginalProduct: 
                                  producer: 
                                           prefix: HA.                                                                                                                                                                                                                                                                                
  jackson: 
       date-format: yyyy-MM-dd HH:mm:ss
banner: 
       charset: UTF-8 # Banner file encoding.
       location: classpath:banner/banner.txt # Banner file location.
       image: 
             location: classpath:banner/yan.png # Banner image file location (jpg/png can also be used).