package com.shangpin.iog.vinicco;

import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;

import org.apache.log4j.Logger;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.shangpin.iog.app.AppContext;
import com.shangpin.iog.vinicco.service.FetchProduct;

public class Startup {
	private static Logger log = Logger.getLogger("info");

	private static ApplicationContext factory;

	private static ResourceBundle bdl = null;

	public static String supplierId;

	private static Map<String, String> brandMap = new HashMap<String, String>();

	private static Map<String, String> categoryMap = new HashMap<String, String>();

	private static String[] brandArray = { "3.1 Philip Lim".toUpperCase(), "Alexander Wang".toUpperCase(), "Ash".toUpperCase(),
			"Balenciaga".toUpperCase(), "Bally".toUpperCase(), "Bottega Veneta".toUpperCase(), "Burberry".toUpperCase(),
			"Bvlgari".toUpperCase(), "Celine".toUpperCase(), "Chloe".toUpperCase(), "Coach".toUpperCase(), "Dior Homme".toUpperCase(),
			"Dolce Gabanna".toUpperCase(), "DSQUARED2".toUpperCase(), "Ermenegildo Zegna".toUpperCase(), "Fendi".toUpperCase(),
			"Furla".toUpperCase(), "Giuseppe Zanotti".toUpperCase(), "Givenchy".toUpperCase(), "Gucci".toUpperCase(),
			"Issey Miyake".toUpperCase(), "Jimmy Choo".toUpperCase(), "Kenzo".toUpperCase(), "Lanvin".toUpperCase(),
			"Longchamp".toUpperCase(), "Love  Moschino".toUpperCase(), "Marc by Marc Jacob".toUpperCase(), "Marc Jacobs".toUpperCase(),
			"MCM".toUpperCase(), "Michael Kors".toUpperCase(), "Moncler".toUpperCase(), "Monster".toUpperCase(), "Moschino".toUpperCase(),
			"NEIL BARRETT".toUpperCase(), "Paul & Shark".toUpperCase(), "Paul Smith".toUpperCase(), "Philipp Plein".toUpperCase(),
			"Saint Laurent".toUpperCase(), "Salvatore Ferragamo".toUpperCase(), "See By Chloé".toUpperCase(),
			"Stella Mccartney".toUpperCase(), "Tod's ".toUpperCase(), "UGG".toUpperCase(), "Valentino".toUpperCase(),
			"Versace".toUpperCase(), "Z Zegna".toUpperCase() };

	private static String name;

	private static String password;
	
	public static String storagePath;

	static {
		if (null == bdl)
			bdl = ResourceBundle.getBundle("conf");
		supplierId = bdl.getString("supplierId");
		name = bdl.getString("name");
		password = bdl.getString("password");
		storagePath = bdl.getString("storagePath");
		// 初始化品牌
		brandMap.put("ALAIA PARIS".toUpperCase(), "X3");
		brandMap.put("ALBERTO GUARDIANI".toUpperCase(), "87");
		brandMap.put("ALBERTO GUARDIANI DRIVE".toUpperCase(), "A;");
		brandMap.put("ALBERTO PREMI".toUpperCase(), "HQ");
		brandMap.put("ALEJANDRO INGELMO".toUpperCase(), "4A");
		brandMap.put("ALESSANDRA DE TOMASO".toUpperCase(), "EU");
		brandMap.put("ALESSANDRO GHERARDI".toUpperCase(), "7J");
		brandMap.put("ALEXANDER WANG".toUpperCase(), "AW");
		brandMap.put("ALEXIA".toUpperCase(), "AX");
		brandMap.put("AMI".toUpperCase(), "XA");
		brandMap.put("AN ITALIAN THEORY".toUpperCase(), "A=");
		brandMap.put("ANTHONY VACCARELLO".toUpperCase(), "GZ");
		brandMap.put("ANYA HINDMARCH".toUpperCase(), "AI");
		brandMap.put("AREA BY BARBARA BOLOGNA".toUpperCase(), "XS");
		brandMap.put("ARMANI COLLEZIONI".toUpperCase(), "1Z");
		brandMap.put("ASH".toUpperCase(), "A5");
		brandMap.put("ASH STUDIO PARIS".toUpperCase(), "DJ");
		brandMap.put("ATELIER VLISCO".toUpperCase(), "0A");
		brandMap.put("ATOLL PALME".toUpperCase(), "A\\");
		brandMap.put("AU SOLEIL DE SAINT TROPEZ".toUpperCase(), "AF");
		brandMap.put("AVANT TOI".toUpperCase(), "65");
		brandMap.put("AVIU".toUpperCase(), "2A");
		brandMap.put("AVN".toUpperCase(), "A/");
		brandMap.put("B-USED".toUpperCase(), "0B");
		brandMap.put("BADURA".toUpperCase(), "UD");
		brandMap.put("BALENCIAGA".toUpperCase(), "BA");
		brandMap.put("BALLY".toUpperCase(), "BL");
		brandMap.put("BALMAIN".toUpperCase(), "B1");
		brandMap.put("BARK".toUpperCase(), "95");
		brandMap.put("BB WASHED MEN BY BRUNO BORDESE".toUpperCase(), "1B");
		brandMap.put("BILLIONAIRE ITALIAN COUTURE".toUpperCase(), "9B");
		brandMap.put("BLACK BELIEVE".toUpperCase(), "ZO");
		brandMap.put("BLACK CORAL".toUpperCase(), "KY");
		brandMap.put("BLANCHA".toUpperCase(), "B2");
		brandMap.put("BLANK".toUpperCase(), "BN");
		brandMap.put("BLEULAB".toUpperCase(), "BK");
		brandMap.put("BOGLIOLI".toUpperCase(), "X6");
		brandMap.put("BOTTEGA VENETA".toUpperCase(), "BV");
		brandMap.put("BRAGHERIA ITALIANA".toUpperCase(), "XB");
		brandMap.put("BRIAN DALES".toUpperCase(), "BD");
		brandMap.put("BRUNELLO CUCINELLI".toUpperCase(), "53");
		brandMap.put("BRUNO BORDESE".toUpperCase(), "B5");
		brandMap.put("BULGARI".toUpperCase(), "B3");
		brandMap.put("BULK".toUpperCase(), "K6");
		brandMap.put("BURBERRY".toUpperCase(), "3C");
		brandMap.put("BURBERRY BRIT".toUpperCase(), "BU");
		brandMap.put("BURBERRY HERITAGE".toUpperCase(), "DW");
		brandMap.put("BURBERRY LONDON".toUpperCase(), "5B");
		brandMap.put("BURBERRY PRORSUM".toUpperCase(), "BP");
		brandMap.put("BUSCEMI".toUpperCase(), "9C");
		brandMap.put("BUXTON PERFUMES".toUpperCase(), "7X");
		brandMap.put("BY WALID".toUpperCase(), "J7");
		brandMap.put("C.P. COMPANY".toUpperCase(), "5L");
		brandMap.put("CANADA GOOSE".toUpperCase(), "51");
		brandMap.put("CAR SHOE".toUpperCase(), "C0");
		brandMap.put("CARROLL".toUpperCase(), "CJ");
		brandMap.put("CARVEN".toUpperCase(), "C4");
		brandMap.put("CASADEI".toUpperCase(), "CD");
		brandMap.put("CELINE".toUpperCase(), "CE");
		brandMap.put("CELLAR DOOR".toUpperCase(), "C3");
		brandMap.put("CHARLOTTE".toUpperCase(), "5C");
		brandMap.put("CHARLOTTE OLYMPIA".toUpperCase(), "U*");
		brandMap.put("CHIARA FERRAGNI".toUpperCase(), "CH");
		brandMap.put("CHLOE'".toUpperCase(), "CL");
		brandMap.put("CHRISTIAN DIOR".toUpperCase(), "CZ");
		brandMap.put("CINZIA ARAIA".toUpperCase(), "31");
		brandMap.put("CMFR".toUpperCase(), "C*");
		brandMap.put("COACH".toUpperCase(), "CK");
		brandMap.put("COMME DES GARCONS".toUpperCase(), "CO");
		brandMap.put("COMME DES GARCONS PLAY".toUpperCase(), "CY");
		brandMap.put("CORSINELABEDOLI".toUpperCase(), "J9");
		brandMap.put("CORTI".toUpperCase(), "C=");
		brandMap.put("COSTUME NATIONAL".toUpperCase(), "CN");
		brandMap.put("COURREGES".toUpperCase(), "4C");
		brandMap.put("CURRENT ELLIOTT".toUpperCase(), "EO");
		brandMap.put("CUTULI CULT".toUpperCase(), "1C");
		brandMap.put("DAKS".toUpperCase(), "78");
		brandMap.put("DAMATRA'".toUpperCase(), "TX");
		brandMap.put("DANIELE FIESOLI".toUpperCase(), "DF");
		brandMap.put("DARK SHADOW".toUpperCase(), "8D");
		brandMap.put("DEGLUPTA".toUpperCase(), "7D");
		brandMap.put("DENIM BY ALEXANDER WANG".toUpperCase(), "C.");
		brandMap.put("DESMO".toUpperCase(), "2E");
		brandMap.put("DESTIN SURL".toUpperCase(), "DE");
		brandMap.put("DIEGO VANASSIBARA".toUpperCase(), "J5");
		brandMap.put("DIOR HOMME".toUpperCase(), "CR");
		brandMap.put("DOLCE&GABBANA".toUpperCase(), "DO");
		brandMap.put("DONDUP".toUpperCase(), "DP");
		brandMap.put("DONDUP HISTORICAL ISLAND".toUpperCase(), "D0");
		brandMap.put("DREAMYOURSELF".toUpperCase(), "XD");
		brandMap.put("DROME".toUpperCase(), "D4");
		brandMap.put("DRY LAKE".toUpperCase(), "2D");
		brandMap.put("DSQUARED2".toUpperCase(), "D2");
		brandMap.put("DUNHILL LONDON".toUpperCase(), "D*");
		brandMap.put("DUVETICA".toUpperCase(), "DU");
		brandMap.put("D1 MILANO".toUpperCase(), "DX");
		brandMap.put("EDUARDO WONGVALLE".toUpperCase(), "34");
		brandMap.put("ELLA".toUpperCase(), "EX");
		brandMap.put("ELLERY".toUpperCase(), "HV");
		brandMap.put("EMANUELE BICOCCHI".toUpperCase(), "EB");
		brandMap.put("EMILIO PUCCI".toUpperCase(), "ED");
		brandMap.put("EMPORIO ARMANI".toUpperCase(), "E4");
		brandMap.put("EQUIPMENT FEMME".toUpperCase(), "38");
		brandMap.put("EQUPMENT PER GARANCE DORE'".toUpperCase(), "UE");
		brandMap.put("ERMENEGILDO ZEGNA".toUpperCase(), "ZG");
		brandMap.put("ESCENTRIC MOLECULES".toUpperCase(), "EM");
		brandMap.put("ESSENTIEL ANTWERP".toUpperCase(), "G0");
		brandMap.put("ETRO".toUpperCase(), "ET");
		brandMap.put("ETRO CLASSIC".toUpperCase(), "EZ");
		brandMap.put("ETRO PROFUMI".toUpperCase(), "E1");
		brandMap.put("EVIL".toUpperCase(), "EV");
		brandMap.put("EYS".toUpperCase(), "29");
		brandMap.put("FABIANA FILIPPI".toUpperCase(), "FD");
		brandMap.put("FAITH CONNEXION".toUpperCase(), "O7");
		brandMap.put("FAUSTO PUGLISI".toUpperCase(), "F8");
		brandMap.put("FEDERICA SASSELLA".toUpperCase(), "X0");
		brandMap.put("FEMME BY MICHELE ROSSI".toUpperCase(), "F5");
		brandMap.put("FENDI".toUpperCase(), "FE");
		brandMap.put("FESSURA".toUpperCase(), "F*");
		brandMap.put("FILLING PIECES".toUpperCase(), "F3");
		brandMap.put("FLOGG".toUpperCase(), "FO");
		brandMap.put("FLOS FLORIS".toUpperCase(), "64");
		brandMap.put("FM CINTURE".toUpperCase(), "70");
		brandMap.put("FOR LOVE & LEMONS".toUpperCase(), "J8");
		brandMap.put("FRAME".toUpperCase(), "FR");
		brandMap.put("FRANKIE MORELLO".toUpperCase(), "FM");
		brandMap.put("FRED PERRY".toUpperCase(), "HS");
		brandMap.put("FURIAH".toUpperCase(), "FQ");
		brandMap.put("FURLA".toUpperCase(), "FH");
		brandMap.put("GABRIELE PASINI".toUpperCase(), "2J");
		brandMap.put("GENETIC DENIM".toUpperCase(), "G1");
		brandMap.put("GERTRUDE".toUpperCase(), "GH");
		brandMap.put("GIACOMORELLI".toUpperCase(), "G8");
		brandMap.put("GIADA BENINCASA".toUpperCase(), "N9");
		brandMap.put("GIAMBA".toUpperCase(), "N5");
		brandMap.put("GIANNI CHIARINI".toUpperCase(), "8Z");
		brandMap.put("GIORGIO ARMANI".toUpperCase(), "G5");
		brandMap.put("GIORGIO BRATO".toUpperCase(), "8G");
		brandMap.put("GIUSEPPE ZANOTTI".toUpperCase(), "ZB");
		brandMap.put("GIVENCHY".toUpperCase(), "GI");
		brandMap.put("GLOBE TROTTER".toUpperCase(), "81");
		brandMap.put("GOLDEN LANE".toUpperCase(), "9X");
		brandMap.put("GRIME OUT".toUpperCase(), "XG");
		brandMap.put("GUCCI".toUpperCase(), "GU");
		brandMap.put("GUM BY GIANNI CHIARINI".toUpperCase(), "ZZ");
		brandMap.put("HAIDER ACKERMANN".toUpperCase(), "H5");
		brandMap.put("HARMONY".toUpperCase(), "HN");
		brandMap.put("HBS".toUpperCase(), "GS");
		brandMap.put("HERNO".toUpperCase(), "HR");
		brandMap.put("HERVE CHAPELIER".toUpperCase(), "HC");
		brandMap.put("HERVE LEGER".toUpperCase(), "HL");
		brandMap.put("HMN23".toUpperCase(), "KG");
		brandMap.put("HOGAN".toUpperCase(), "77");
		brandMap.put("HOGAN REBEL".toUpperCase(), "54");
		brandMap.put("HOGAN REBEL LES TWINS".toUpperCase(), "T0");
		brandMap.put("HOOD BY AIR".toUpperCase(), "HJ");
		brandMap.put("HOSIO".toUpperCase(), "H7");
		brandMap.put("HOTEL PARTICULIER".toUpperCase(), "ZP");
		brandMap.put("HTC".toUpperCase(), "H3");
		brandMap.put("HUDSON".toUpperCase(), "FP");
		brandMap.put("HYDROGEN".toUpperCase(), "HY");
		brandMap.put("HYDROGEN SPORT".toUpperCase(), "H2");
		brandMap.put("IL BISONTE".toUpperCase(), "IB");
		brandMap.put("ILLESTEVA".toUpperCase(), "II");
		brandMap.put("ILLOGIQUE".toUpperCase(), "I5");
		brandMap.put("IN STAR".toUpperCase(), "IU");
		brandMap.put("IN THE BOX".toUpperCase(), "IX");
		brandMap.put("ISABEL BENENATO".toUpperCase(), "97");
		brandMap.put("ISABEL MARANT".toUpperCase(), "IA");
		brandMap.put("ISABEL MARANT ETOILE".toUpperCase(), "EE");
		brandMap.put("ISHIKAWA".toUpperCase(), "IS");
		brandMap.put("ISHIKAWA".toUpperCase(), "23");
		brandMap.put("ISSEY MIYAKE".toUpperCase(), "IY");
		brandMap.put("ITALIAN CRAZY".toUpperCase(), "IP");
		brandMap.put("J.W. ANDERSON".toUpperCase(), "WJ");
		brandMap.put("J.W.ANDERSON".toUpperCase(), "JV");
		brandMap.put("JACOB CHOEN".toUpperCase(), "DZ");
		brandMap.put("JACQUES MORGAN".toUpperCase(), "27");
		brandMap.put("JAMES GOLDSTEIN".toUpperCase(), "J2");
		brandMap.put("JAMES PERSE".toUpperCase(), "JM");
		brandMap.put("JBRAND".toUpperCase(), "JB");
		brandMap.put("JC PLAY".toUpperCase(), "JD");
		brandMap.put("JEFFREY CAMPBELL".toUpperCase(), "JF");
		brandMap.put("JIMMY CHOO".toUpperCase(), "JC");
		brandMap.put("JOSHUA SANDERS".toUpperCase(), "J0");
		brandMap.put("JULIAN KEEN HOMME".toUpperCase(), "J1");
		brandMap.put("KANGRA CASHMERE".toUpperCase(), "62");
		brandMap.put("KARSSEN".toUpperCase(), "JT");
		brandMap.put("KART".toUpperCase(), "KF");
		brandMap.put("KENZO".toUpperCase(), "KN");
		brandMap.put("KRISVANASSCHE".toUpperCase(), "KR");
		brandMap.put("KUBERA 108".toUpperCase(), "K8");
		brandMap.put("L.VENTURINI".toUpperCase(), "LQ");
		brandMap.put("LANVIN".toUpperCase(), "LA");
		brandMap.put("LARDINI".toUpperCase(), "48");
		brandMap.put("LAURENCE DACADE".toUpperCase(), "Y1");
		brandMap.put("LE CAPRESI".toUpperCase(), "2L");
		brandMap.put("LE CUIR PERDU".toUpperCase(), "4L");
		brandMap.put("LEO".toUpperCase(), "L0");
		brandMap.put("LES (ART)ISTS".toUpperCase(), "E8");
		brandMap.put("LES BENJAMINS".toUpperCase(), "66");
		brandMap.put("LES CHIFFONIERS".toUpperCase(), "LC");
		brandMap.put("LES HOMMES".toUpperCase(), "LH");
		brandMap.put("LES HOMMES URBAN".toUpperCase(), "FN");
		brandMap.put("LOEWE".toUpperCase(), "LO");
		brandMap.put("LOOK ME".toUpperCase(), "LK");
		brandMap.put("LOSERS".toUpperCase(), "LW");
		brandMap.put("LOUIS LEEMAN".toUpperCase(), "LG");
		brandMap.put("LUCIEN PELLAT-FINET".toUpperCase(), "6L");
		brandMap.put("MACKINTOSH".toUpperCase(), "D=");
		brandMap.put("MAIYET".toUpperCase(), "9E");
		brandMap.put("MANUEL FACCHINI".toUpperCase(), "GX");
		brandMap.put("MARC BY MARC".toUpperCase(), "MB");
		brandMap.put("MARC JACOBS".toUpperCase(), "MJ");
		brandMap.put("MARCELO BURLON".toUpperCase(), "17");
		brandMap.put("MARCO LAGANA'".toUpperCase(), "I9");
		brandMap.put("MARCO LAGANA'".toUpperCase(), "M!");
		brandMap.put("MARCOMILAN".toUpperCase(), "XM");
		brandMap.put("MARESTER".toUpperCase(), "H9");
		brandMap.put("MARNI".toUpperCase(), "MA");
		brandMap.put("MARQUIS AN'DOGE".toUpperCase(), "NF");
		brandMap.put("MARYLING".toUpperCase(), "ZM");
		brandMap.put("MASNADA".toUpperCase(), "JL");
		brandMap.put("MASTER COAT".toUpperCase(), "06");
		brandMap.put("MATTHEW WILLIAMSON".toUpperCase(), "+3");
		brandMap.put("MAUNA KEA".toUpperCase(), "WK");
		brandMap.put("MAURON".toUpperCase(), "24");
		brandMap.put("MAX MARA".toUpperCase(), "DA");
		brandMap.put("MAX MARA ATELIER".toUpperCase(), "I8");
		brandMap.put("MAX MARA CITY".toUpperCase(), "I7");
		brandMap.put("MAX MARA SPORTMAX".toUpperCase(), "I6");
		brandMap.put("MAX MARA SPX CODE".toUpperCase(), "S.");
		brandMap.put("MAX MARA STUDIO".toUpperCase(), "00");
		brandMap.put("MAXIME SIMOENS".toUpperCase(), "ZS");
		brandMap.put("MC GEORGE OF SCOTLAND".toUpperCase(), "MX");
		brandMap.put("MCM".toUpperCase(), "9F");
		brandMap.put("MDK".toUpperCase(), "K5");
		brandMap.put("MD75".toUpperCase(), "F0");
		brandMap.put("MELISSA".toUpperCase(), "M8");
		brandMap.put("MEO FUSCIUNI".toUpperCase(), "IQ");
		brandMap.put("METRADAMO".toUpperCase(), "26");
		brandMap.put("MEXICANA".toUpperCase(), "36");
		brandMap.put("MIA BAG".toUpperCase(), "07");
		brandMap.put("MICHAEL KORS".toUpperCase(), "3K");
		brandMap.put("MICHAEL MICHAEL KORS".toUpperCase(), "K3");
		brandMap.put("MIHARA YASUHIRO".toUpperCase(), "9J");
		brandMap.put("MIISTA".toUpperCase(), "M?");
		brandMap.put("MINIMAL TO".toUpperCase(), "HI");
		brandMap.put("MIRKO BUFFINI".toUpperCase(), "5J");
		brandMap.put("MOA".toUpperCase(), "FY");
		brandMap.put("MODE DE VIE".toUpperCase(), "3J");
		brandMap.put("MONCLER".toUpperCase(), "MN");
		brandMap.put("MONCLER BLACKOUT".toUpperCase(), "O9");
		brandMap.put("MONCLER CAPSULE FEMME".toUpperCase(), "93");
		brandMap.put("MONCLER CAPSULE HOMME".toUpperCase(), "92");
		brandMap.put("MONCLER GAMME ROUGE".toUpperCase(), "0M");
		brandMap.put("MONCLER GRENOBLE".toUpperCase(), "91");
		brandMap.put("MONCLER R".toUpperCase(), "M*");
		brandMap.put("MONOM".toUpperCase(), "U2");
		brandMap.put("MOOSE KNUCKLES".toUpperCase(), "M=");
		brandMap.put("MOSCHINO".toUpperCase(), "8M");
		brandMap.put("MOSCHINO BOUTIQUE".toUpperCase(), "E9");
		brandMap.put("MOSCHINO CAPSULE".toUpperCase(), "ER");
		brandMap.put("MOSCHINO CHEAP AND CHIC".toUpperCase(), "MC");
		brandMap.put("MOSCHINO COUTURE !".toUpperCase(), "ML");
		brandMap.put("MSGM".toUpperCase(), "2X");
		brandMap.put("MUA MUA DOLLS".toUpperCase(), "1E");
		brandMap.put("MULBERRY".toUpperCase(), "MU");
		brandMap.put("MUT".toUpperCase(), "E0");
		brandMap.put("MUUBAA".toUpperCase(), "MY");
		brandMap.put("MYTHS".toUpperCase(), "UW");
		brandMap.put("M2MALLETIER".toUpperCase(), "M:");
		brandMap.put("N 21".toUpperCase(), "N4");
		brandMap.put("NEHERA".toUpperCase(), "N6");
		brandMap.put("NEHERA SHOW".toUpperCase(), "N*");
		brandMap.put("NEIL BARRETT".toUpperCase(), "NB");
		brandMap.put("NENA RISTICH".toUpperCase(), "WP");
		brandMap.put("NEVER ENOUGH".toUpperCase(), "ND");
		brandMap.put("NEW ERA".toUpperCase(), "WR");
		brandMap.put("NHERO".toUpperCase(), "9N");
		brandMap.put("NICHOLAS KIRKWOOD".toUpperCase(), "NK");
		brandMap.put("NIKE".toUpperCase(), "G4");
		brandMap.put("NO ARTIGIANI ITALIANI".toUpperCase(), "XO");
		brandMap.put("NOBIS".toUpperCase(), "N=");
		brandMap.put("NUMERO 00".toUpperCase(), "N+");
		brandMap.put("NYOU LUX TATTOO".toUpperCase(), "N7");
		brandMap.put("OBVIOUS".toUpperCase(), "4J");
		brandMap.put("OFF-WHITE".toUpperCase(), "OF");
		brandMap.put("OFFICINE CREATIVE".toUpperCase(), "OC");
		brandMap.put("ONE OFF".toUpperCase(), "OA");
		brandMap.put("ONE TEASPOON".toUpperCase(), "J3");
		brandMap.put("ONES".toUpperCase(), "OS");
		brandMap.put("OPENING CEREMONY".toUpperCase(), "EQ");
		brandMap.put("OSTWALD HELGASON".toUpperCase(), "OD");
		brandMap.put("OUI,ODILE!".toUpperCase(), "OU");
		brandMap.put("OVERCOME".toUpperCase(), "O+");
		brandMap.put("PACO CHICANO".toUpperCase(), "40");
		brandMap.put("PACO RABANNE".toUpperCase(), "PB");
		brandMap.put("PAIGE".toUpperCase(), "PJ");
		brandMap.put("PALEA'".toUpperCase(), "NP");
		brandMap.put("PALOMITAS BY PALOMA MARCELO'".toUpperCase(), "JP");
		brandMap.put("PAOLO PECORA".toUpperCase(), "PE");
		brandMap.put("PAUL & SHARK".toUpperCase(), "6J");
		brandMap.put("PAUL SMITH".toUpperCase(), "PS");
		brandMap.put("PAULA CADEMARTORI".toUpperCase(), "50");
		brandMap.put("PEACE BY VSP".toUpperCase(), "VP");
		brandMap.put("PEPPERCHOCOLATE".toUpperCase(), "3X");
		brandMap.put("PHILIPP PLEIN".toUpperCase(), "6P");
		brandMap.put("PHILIPPE MODEL".toUpperCase(), "P3");
		brandMap.put("PHILLIP LIM".toUpperCase(), "PP");
		brandMap.put("PHILOSOPHY DI LORENZO SERAFINI".toUpperCase(), "P-");
		brandMap.put("PIANOFORTE".toUpperCase(), "D9");
		brandMap.put("PICCIONE PICCIONE".toUpperCase(), "X8");
		brandMap.put("PIERRE BALMAIN".toUpperCase(), "1P");
		brandMap.put("PIERRE HARDY".toUpperCase(), "PH");
		brandMap.put("PINKO".toUpperCase(), "PI");
		brandMap.put("PINKO BLACK".toUpperCase(), "8P");
		brandMap.put("PINKO GREY".toUpperCase(), "0P");
		brandMap.put("PINKO TAG".toUpperCase(), "D7");
		brandMap.put("PINKO TRICOT".toUpperCase(), "9P");
		brandMap.put("PORTS \"by Christopher Makos\"".toUpperCase(), "B=");
		brandMap.put("PREACH".toUpperCase(), "I0");
		brandMap.put("PRINCIPE DI BOLOGNA".toUpperCase(), "4+");
		brandMap.put("PROENZA SCHOULER".toUpperCase(), "PZ");
		brandMap.put("PS PAUL SMITH".toUpperCase(), "05");
		brandMap.put("PT ICON".toUpperCase(), "03");
		brandMap.put("PT0W".toUpperCase(), "Y5");
		brandMap.put("PT01".toUpperCase(), "01");
		brandMap.put("PT01 THOMAS NEAL'S".toUpperCase(), "Y7");
		brandMap.put("PT05".toUpperCase(), "RQ");
		brandMap.put("PUMA BY ALEXANDER MCQUEEN".toUpperCase(), "4P");
		brandMap.put("PUMA BY HUSSEIN CHALAYAN".toUpperCase(), "82");
		brandMap.put("PUMA BY MIHARA YASUHIRO".toUpperCase(), "16");
		brandMap.put("PURPLE DE NIMES".toUpperCase(), "25");
		brandMap.put("P13".toUpperCase(), "61");
		brandMap.put("QIODO".toUpperCase(), "1Q");
		brandMap.put("RAF MOORE".toUpperCase(), "4X");
		brandMap.put("RAPARO".toUpperCase(), "RP");
		brandMap.put("RAT ROEN".toUpperCase(), "56");
		brandMap.put("RATTI COLLEZIONI".toUpperCase(), "R:");
		brandMap.put("RAW TYPE".toUpperCase(), "ZW");
		brandMap.put("REBECCA MINKOFF".toUpperCase(), "RF");
		brandMap.put("RECEPTION".toUpperCase(), "RN");
		brandMap.put("REED KRAKOFF".toUpperCase(), "R2");
		brandMap.put("REGINA D'ITALIA".toUpperCase(), "RX");
		brandMap.put("REIGN".toUpperCase(), "R6");
		brandMap.put("RELIVE".toUpperCase(), "RL");
		brandMap.put("RH45".toUpperCase(), "RY");
		brandMap.put("RICK OWENS".toUpperCase(), "OW");
		brandMap.put("RICK OWENS LILIES".toUpperCase(), "02");
		brandMap.put("RIDERS ON THE STORM".toUpperCase(), "1A");
		brandMap.put("RIZAL".toUpperCase(), "H8");
		brandMap.put("ROBERTA DI CAMERINO".toUpperCase(), "RB");
		brandMap.put("ROBERTO CAVALLI".toUpperCase(), "RC");
		brandMap.put("ROCCO P.".toUpperCase(), "RJ");
		brandMap.put("ROLANDO TREDICI".toUpperCase(), "R*");
		brandMap.put("ROSANTICA".toUpperCase(), "R9");
		brandMap.put("ROSSIGNOL".toUpperCase(), "R0");
		brandMap.put("RUJIRU".toUpperCase(), "5R");
		brandMap.put("RUTHIE DAVIS".toUpperCase(), "RU");
		brandMap.put("R13".toUpperCase(), "F9");
		brandMap.put("SACAI".toUpperCase(), "63");
		brandMap.put("SACAI LUCK".toUpperCase(), "8Y");
		brandMap.put("SAINT LAURENT".toUpperCase(), "YP");
		brandMap.put("SALVATORE FERRAGAMO".toUpperCase(), "SF");
		brandMap.put("SALVATORE SANTORO".toUpperCase(), "9Y");
		brandMap.put("SAM EDELMAN".toUpperCase(), "E5");
		brandMap.put("SAN ANDRES".toUpperCase(), "FV");
		brandMap.put("SANTANIELLO BIAGIO".toUpperCase(), "72");
		brandMap.put("SATURNINO EYEWEAR".toUpperCase(), "AJ");
		brandMap.put("SAUCONY".toUpperCase(), "8J");
		brandMap.put("SEBOY'S".toUpperCase(), "15");
		brandMap.put("SEE BY CHLOE CHRISTMAS".toUpperCase(), "S+");
		brandMap.put("SEE BY CHLOE'".toUpperCase(), "SC");
		brandMap.put("SELEZIONE BASICA".toUpperCase(), "9Z");
		brandMap.put("SELF-PORTRAIT".toUpperCase(), "P0");
		brandMap.put("SENSO".toUpperCase(), "J6");
		brandMap.put("SERGIO ROSSI".toUpperCase(), "S3");
		brandMap.put("SEVEN".toUpperCase(), "SE");
		brandMap.put("SIGERSON MORRISON".toUpperCase(), "90");
		brandMap.put("SILENT+BLESSED".toUpperCase(), "WS");
		brandMap.put("SIMONETTA RAVIZZA".toUpperCase(), "SZ");
		brandMap.put("SKINGRAFT".toUpperCase(), "0S");
		brandMap.put("SNOBBY SHEEP".toUpperCase(), "SN");
		brandMap.put("SONIA RYKIEL".toUpperCase(), "6S");
		brandMap.put("SOPHIE HULME".toUpperCase(), "9G");
		brandMap.put("SPORTMAX".toUpperCase(), "DD");
		brandMap.put("SPRINGA".toUpperCase(), "1S");
		brandMap.put("STELLA McCARTNEY".toUpperCase(), "SM");
		brandMap.put("STONE ISLAND".toUpperCase(), "SK");
		brandMap.put("STORIES-MILANO".toUpperCase(), "FZ");
		brandMap.put("STUTTERHEIM RAINCOATS".toUpperCase(), "HG");
		brandMap.put("SUCRE".toUpperCase(), "13");
		brandMap.put("SUECOMMA BONNIE".toUpperCase(), "B0");
		brandMap.put("SUNBOO".toUpperCase(), "S0");
		brandMap.put("SUNDAY 21".toUpperCase(), "HZ");
		brandMap.put("SUSANA TRACA".toUpperCase(), "S9");
		brandMap.put("SWAG".toUpperCase(), "S*");
		brandMap.put("T-BY ALEXANDER WANG".toUpperCase(), "32");
		brandMap.put("TATRAS".toUpperCase(), "T6");
		brandMap.put("THE GIGI".toUpperCase(), "6T");
		brandMap.put("THOM BROWN".toUpperCase(), "EI");
		brandMap.put("THREE SOCKS SIDE".toUpperCase(), "T+");
		brandMap.put("TOD'S".toUpperCase(), "T2");
		brandMap.put("TOD'S T-PROJECT".toUpperCase(), "TP");
		brandMap.put("TOM FORD".toUpperCase(), "T8");
		brandMap.put("TOMBOLINI".toUpperCase(), "Y2");
		brandMap.put("TONELLO".toUpperCase(), "TO");
		brandMap.put("TRANSIT".toUpperCase(), "42");
		brandMap.put("TRE CINQUE SETTE".toUpperCase(), "T*");
		brandMap.put("TRE CINQUE SETTE".toUpperCase(), "TT");
		brandMap.put("TRES CHIC S.A.R.T.O.R.I.A.L.".toUpperCase(), "35");
		brandMap.put("TRUE NYC".toUpperCase(), "TN");
		brandMap.put("TRUE RELIGION".toUpperCase(), "TR");
		brandMap.put("TRUE ROYAL".toUpperCase(), "55");
		brandMap.put("TRUE TRADITION".toUpperCase(), "T3");
		brandMap.put("TRUSSARDI".toUpperCase(), "TM");
		brandMap.put("TRUSSARDI JEANS".toUpperCase(), "TZ");
		brandMap.put("TUMI".toUpperCase(), "4T");
		brandMap.put("TURQUOISE".toUpperCase(), "ZI");
		brandMap.put("U AVIU".toUpperCase(), "UA");
		brandMap.put("UGG AUSTRALIA".toUpperCase(), "U1");
		brandMap.put("UGG KID'S".toUpperCase(), "X2");
		brandMap.put("UNFLEUR".toUpperCase(), "UB");
		brandMap.put("UNGARO".toUpperCase(), "47");
		brandMap.put("UNTITLED".toUpperCase(), "U3");
		brandMap.put("VALENTINO".toUpperCase(), "VL");
		brandMap.put("VALENTINO GARAVANI".toUpperCase(), "V2");
		brandMap.put("VALENTINO PAP".toUpperCase(), "V5");
		brandMap.put("VALENTINO PAP SPORTSWEAR".toUpperCase(), "1V");
		brandMap.put("VALENTINO RED".toUpperCase(), "V3");
		brandMap.put("VALEXTRA".toUpperCase(), "V8");
		brandMap.put("VAR/CITY".toUpperCase(), "9D");
		brandMap.put("VERSACE".toUpperCase(), "VE");
		brandMap.put("VERSACE COLLECTION".toUpperCase(), "V0");
		brandMap.put("VERSUS".toUpperCase(), "VU");
		brandMap.put("VICTORIA BECKHAM".toUpperCase(), "BC");
		brandMap.put("VIKTOR & ROLF".toUpperCase(), "VK");
		brandMap.put("VIOLANTI".toUpperCase(), "DQ");
		brandMap.put("VITTORIO BRANCHIZIO".toUpperCase(), "H0");
		brandMap.put("VON VONNI".toUpperCase(), "39");
		brandMap.put("V73".toUpperCase(), "VC");
		brandMap.put("WHITE RAVEN".toUpperCase(), "W2");
		brandMap.put("WOOD'D".toUpperCase(), "W3");
		brandMap.put("YEEZY".toUpperCase(), "JZ");
		brandMap.put("YOON".toUpperCase(), "YN");
		brandMap.put("YVES SAINT LAURENT".toUpperCase(), "YS");
		brandMap.put("Y3".toUpperCase(), "Y3");
		brandMap.put("Y3 BY YOHJI YAMAMOTO".toUpperCase(), "YY");
		brandMap.put("ZAGLIANI".toUpperCase(), "ZA");
		brandMap.put("ZANELLATO".toUpperCase(), "ZC");
		brandMap.put("11B ELEVEN BAR".toUpperCase(), "JQ");
		brandMap.put("3.3".toUpperCase(), "O3");
		brandMap.put("5 PREVIEW".toUpperCase(), "5P");
		brandMap.put("75 FAUBOURG".toUpperCase(), "X7");

		// 初始化分类
		categoryMap.put("ACCESSORIES", "2");
		categoryMap.put("BAGS", "4");
		categoryMap.put("CLOTHING", "1");
		categoryMap.put("JEWELLERY", "5");
		categoryMap.put("SHOES", "3");

	}

	private static void loadSpringContext() {
		factory = new AnnotationConfigApplicationContext(AppContext.class);
	}

	public static void main(String[] args) {

		// 加载spring
		log.info("----拉取vinicco数据开始----");
		loadSpringContext();
		log.info("----初始SPRING成功----");
		// 拉取数据
		FetchProduct fetchProduct = (FetchProduct) factory.getBean("vinicco");
//		String[] brandArray = { "NEIL BARRETT".toUpperCase(), "Paul & Shark".toUpperCase(), "Paul Smith".toUpperCase(), "Philipp Plein".toUpperCase() };
		fetchProduct.fetchProductAndSave(supplierId, brandMap, brandArray, categoryMap, name, password);

		log.info("----拉取vinicco数据完成----");

		System.out.println("-------fetch end---------");
		System.exit(0);
	}

}
