package com.shangpin.iog.sarenza.dto;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class Product {
	private String  ModelName;
	private String  BrandId;
	private String  BrandLabel;
	private String  Title;
	private String  GenderId;
	private String  GenderLabel;
	private String  SubGenderId1;
	private String  SubGenderLabel1;
	private String  SubGenderId2;
	private String  SubGenderLabel2;
	private String  SubGenderId3;
	private String  SubGenderLabel3;
	private String  MainTypeId;
	private String  MainTypeLabel;
	private String  SecondaryType1Id;
	private String  SecondaryTypeLabel;
	private String  SecondaryType2Id;
	private String  SecondaryTypeLabel2;
	private String  SecondaryType3Id;
	private String  SecondaryTypeLabel3;
	private String  SubTypeId1;
	private String  SubTypeLabel1;
	private String  SubTypeId2;
	private String  SubTypeLabel2;
	private String  SubTypeId3;
	private String  SubTypeLabel3;
	private String  SubTypeId4;
	private String  SubTypeLabel4;
	private String  SubTypeId5;
	private String  SubTypeLabel5;
	private String  SubTypeId6;
	private String  SubTypeLabel6;
	private String  Picture1;
	private String  Picture2;
	private String  Picture3;
	private String  Picture4;
	private String  Picture5;
	private String  Picture6;
	private String  Picture7;
	private String  Picture8;
	private String  Picture9;
	private String  Picture1HD;
	private String  Picture2HD;
	private String  Picture3HD;
	private String  Picture4HD;
	private String  Picture5HD;
	private String  Picture6HD;
	private String  Picture7HD;
	private String  Picture8HD;
	private String  Picture9HD;
	private String  SarenzaColorId1;
	private String  SarenzaColorLabel1;
	private String  SarenzaColorId2;
	private String  SarenzaColorLabel2;
	private String  SarenzaColorId3;
	private String  SarenzaColorLabel3;
	private String  SupplierColorId;
	private String  SupplierColorLabel;
	private String  SeasonId;
	private String  SeasonLabel;
	private String  CollectionYear;
	private String  PCID;
	private String  VariantId;
	private String  ProductId;
	private String  SarenzaSize;
	private String  HeelHeight;
	private String  MaterialId;
	private String  MaterialLabel;
	private String  UniverseId1;
	private String  UniverseLabel1;
	private String  UniverseId2;
	private String  UniverseLabel2;
	private String  UniverseId3;
	private String  UniverseLabel3;
	private String  UniverseId4;
	private String  UniverseLabel4;
	private String  CalfWidth;
//	private String  SellingPrice;
//	private String  DefaultPrice;
//	private String  RefPrice;
	private String  Price;
	private String  Description;
	private String  InsoleInsoleMaterialId;
	private String  InsoleMaterialLabel;
	private String  OutsoleMaterialId;
	private String  OutsoleMaterialLabel;
	private String  LiningMaterialId;
	private String  LiningMaterialLabel;
	private String  ManufactureId;
	private String  ManufactureLabel;
	private String  SizeBuyerAdvice;
	private String  StemHeight;
	private String  Stock;
	private String  SupplierSize;
	private String  Length;
	private String  Volume;
	private String  Weight;
	private String  Width;
	private String  Height;
	private String  ProductCode;
	private String  MadeIn;
	
}
